import { ModuleManifest } from '../../core/types/module.types';
import { BusinessType, UserRole } from '../../types/tenant.types';
import { PlanTier, FeatureKey } from '../../config/plan-feature-registry';

export const schoolErpManifest: ModuleManifest = {
    id: 'school-erp',
    version: '1.0.0',
    displayName: 'School ERP / Academic Coaching',
    status: 'active',
    businessTypes: [BusinessType.SCHOOL_ERP],
    requiredPlan: PlanTier.BASIC,
    minRole: UserRole.STAFF,
    featureKeys: [
        FeatureKey.AC_STUDENT_MANAGEMENT,
        FeatureKey.AC_BATCH_MANAGEMENT,
        FeatureKey.AC_COURSE_MANAGEMENT,
        FeatureKey.AC_FEE_MANAGEMENT,
        FeatureKey.AC_ATTENDANCE_MANAGEMENT,
        FeatureKey.AC_FACULTY_MANAGEMENT,
        FeatureKey.AC_EXAM_MANAGEMENT,
        FeatureKey.AC_TIMETABLE_MANAGEMENT,
        FeatureKey.AC_MATERIAL_MANAGEMENT,
        FeatureKey.AC_COMMUNICATION,
        FeatureKey.AC_REPORTS_ANALYTICS,
        FeatureKey.AC_PARENT_PORTAL,
        FeatureKey.AC_STUDENT_PORTAL,
        FeatureKey.AC_NOTIFICATIONS,
        FeatureKey.AC_BULK_OPERATIONS,
        FeatureKey.AC_FINANCIAL_REPORTS,
        FeatureKey.AC_CERTIFICATES,
        FeatureKey.AC_CLASS_SECTION_MANAGEMENT,
        FeatureKey.AC_ACADEMIC_YEAR_MANAGEMENT,
        FeatureKey.AC_LIBRARY_MANAGEMENT,
        FeatureKey.AC_TRANSPORT_MANAGEMENT,
        FeatureKey.AC_REPORT_CARDS,
        FeatureKey.AC_CLASSWISE_FEE,
        FeatureKey.AC_INSTITUTION_CONFIG,
    ],
    lambdaFunctions: [
        'schoolStudents',
        'schoolBatches',
        'schoolCourses',
        'schoolFees',
        'schoolAttendance',
        'schoolFaculty',
        'schoolExams',
        'schoolTimetable',
        'schoolMaterials',
        'schoolCommunication',
        'schoolReports',
        'schoolAdmissions',
        'schoolTransport',
        'schoolLibrary',
        'schoolHostel',
        'schoolBiometric',
        'schoolConcession',
        'schoolDepartments',
        'schoolDocuments',
        'schoolHomework',
        'schoolLeave',
        'schoolLessonPlans',
        'schoolPeriodAttendance',
        'schoolPayslip',
        'schoolRefund',
        'schoolSibling',
        'schoolPayments',
    ],
    wsChannelPrefix: 'school:',
    apiPrefix: '/ac',
    db: {
        skPrefixes: [
            'AC_STUDENT#', 'AC_BATCH#', 'AC_COURSE#', 'AC_FEE#',
            'AC_ATTENDANCE#', 'AC_FACULTY#', 'AC_EXAM#', 'AC_RESULT#',
            'AC_TIMETABLE#', 'AC_MATERIAL#', 'AC_INVOICE#', 'AC_PAYMENT#',
            'AC_NOTIF#', 'AC_DEMO#', 'AC_ID_CARD#', 'AC_EXPENSE#',
        ],
        gsiIndexes: ['GSI1', 'GSI2'],
        requiresWriteSharding: false,
    },
    queues: [
        {
            logicalName: 'SchoolNotificationQueue',
            fifo: false,
            maxReceiveCount: 3,
            visibilityTimeoutSeconds: 60,
        },
        {
            logicalName: 'SchoolFeeReminderQueue',
            fifo: false,
            maxReceiveCount: 3,
            visibilityTimeoutSeconds: 120,
        },
    ],
    eventPatterns: [
        {
            source: 'dukanx.school',
            detailTypes: [
                'student.enrolled', 'fee.due', 'attendance.marked',
                'exam.scheduled', 'result.published', 'notification.sent',
            ],
        },
    ],
    rateLimits: {
        [PlanTier.BASIC]: 100,
        [PlanTier.PRO]: 400,
        [PlanTier.PREMIUM]: 1200,
        [PlanTier.ENTERPRISE]: 8000,
    },
    dependsOn: ['billing'],
    aiToolsEnabled: true,
    marketplaceEligible: false,
};
