// Mocks generated by Mockito 5.4.6 from annotations
// in dukanx/test/integration/customer_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dukanx/core/database/app_database.dart' as _i2;
import 'package:dukanx/core/error/error_handler.dart' as _i4;
import 'package:dukanx/core/repository/bills_repository.dart' as _i6;
import 'package:dukanx/core/repository/customers_repository.dart' as _i9;
import 'package:dukanx/core/services/event_dispatcher.dart' as _i5;
import 'package:dukanx/core/sync/models/sync_types.dart' as _i12;
import 'package:dukanx/core/sync/sync_conflict.dart' as _i11;
import 'package:dukanx/core/sync/sync_manager.dart' as _i3;
import 'package:dukanx/core/sync/sync_queue_state_machine.dart' as _i13;
import 'package:dukanx/models/bill.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncManager_1 extends _i1.SmartFake implements _i3.SyncManager {
  _FakeSyncManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeErrorHandler_2 extends _i1.SmartFake implements _i4.ErrorHandler {
  _FakeErrorHandler_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventDispatcher_3 extends _i1.SmartFake
    implements _i5.EventDispatcher {
  _FakeEventDispatcher_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRepositoryResult_4<T> extends _i1.SmartFake
    implements _i4.RepositoryResult<T> {
  _FakeRepositoryResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncHealthMetrics_5 extends _i1.SmartFake
    implements _i3.SyncHealthMetrics {
  _FakeSyncHealthMetrics_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BillsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillsRepository extends _i1.Mock implements _i6.BillsRepository {
  MockBillsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i3.SyncManager get syncManager =>
      (super.noSuchMethod(
            Invocation.getter(#syncManager),
            returnValue: _FakeSyncManager_1(
              this,
              Invocation.getter(#syncManager),
            ),
          )
          as _i3.SyncManager);

  @override
  _i4.ErrorHandler get errorHandler =>
      (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: _FakeErrorHandler_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          )
          as _i4.ErrorHandler);

  @override
  _i5.EventDispatcher get eventDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#eventDispatcher),
            returnValue: _FakeEventDispatcher_3(
              this,
              Invocation.getter(#eventDispatcher),
            ),
          )
          as _i5.EventDispatcher);

  @override
  _i7.Future<_i4.RepositoryResult<_i8.Bill>> createBill(_i8.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#createBill, [bill]),
            returnValue: _i7.Future<_i4.RepositoryResult<_i8.Bill>>.value(
              _FakeRepositoryResult_4<_i8.Bill>(
                this,
                Invocation.method(#createBill, [bill]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i8.Bill>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i8.Bill>> updateBill(
    _i8.Bill? bill, {
    String? approverId,
    String? editReason,
    DateTime? expectedUpdatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBill,
              [bill],
              {
                #approverId: approverId,
                #editReason: editReason,
                #expectedUpdatedAt: expectedUpdatedAt,
              },
            ),
            returnValue: _i7.Future<_i4.RepositoryResult<_i8.Bill>>.value(
              _FakeRepositoryResult_4<_i8.Bill>(
                this,
                Invocation.method(
                  #updateBill,
                  [bill],
                  {
                    #approverId: approverId,
                    #editReason: editReason,
                    #expectedUpdatedAt: expectedUpdatedAt,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i8.Bill>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i8.Bill>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i7.Future<_i4.RepositoryResult<_i8.Bill>>.value(
              _FakeRepositoryResult_4<_i8.Bill>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i8.Bill>>);

  @override
  _i7.Future<_i4.RepositoryResult<List<_i8.Bill>>> getAll({
    required String? userId,
    String? customerId,
    String? businessId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #userId: userId,
              #customerId: customerId,
              #businessId: businessId,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<List<_i8.Bill>>>.value(
              _FakeRepositoryResult_4<List<_i8.Bill>>(
                this,
                Invocation.method(#getAll, [], {
                  #userId: userId,
                  #customerId: customerId,
                  #businessId: businessId,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<List<_i8.Bill>>>);

  @override
  _i7.Stream<List<_i8.Bill>> watchAll({
    required String? userId,
    String? customerId,
    String? businessId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {
              #userId: userId,
              #customerId: customerId,
              #businessId: businessId,
            }),
            returnValue: _i7.Stream<List<_i8.Bill>>.empty(),
          )
          as _i7.Stream<List<_i8.Bill>>);

  @override
  _i7.Future<_i4.RepositoryResult<bool>> recordPayment({
    required String? userId,
    required String? billId,
    required double? amount,
    required String? paymentMode,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPayment, [], {
              #userId: userId,
              #billId: billId,
              #amount: amount,
              #paymentMode: paymentMode,
              #notes: notes,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#recordPayment, [], {
                  #userId: userId,
                  #billId: billId,
                  #amount: amount,
                  #paymentMode: paymentMode,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<bool>>);

  @override
  _i7.Future<_i4.RepositoryResult<bool>> deletePayment({
    required String? userId,
    required String? paymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [], {
              #userId: userId,
              #paymentId: paymentId,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#deletePayment, [], {
                  #userId: userId,
                  #paymentId: paymentId,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<bool>>);

  @override
  _i7.Future<_i4.RepositoryResult<bool>> updateBillStatus({
    required String? billId,
    required String? status,
    required double? paidAmount,
    double? cashPaid,
    double? onlinePaid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBillStatus, [], {
              #billId: billId,
              #status: status,
              #paidAmount: paidAmount,
              #cashPaid: cashPaid,
              #onlinePaid: onlinePaid,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#updateBillStatus, [], {
                  #billId: billId,
                  #status: status,
                  #paidAmount: paidAmount,
                  #cashPaid: cashPaid,
                  #onlinePaid: onlinePaid,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<bool>>);

  @override
  _i7.Future<_i4.RepositoryResult<bool>> createCorrectionRequest({
    required String? billId,
    required String? customerId,
    required String? message,
    required double? billAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCorrectionRequest, [], {
              #billId: billId,
              #customerId: customerId,
              #message: message,
              #billAmount: billAmount,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#createCorrectionRequest, [], {
                  #billId: billId,
                  #customerId: customerId,
                  #message: message,
                  #billAmount: billAmount,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<bool>>);

  @override
  _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>> getTodaySummary(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, [userId]),
            returnValue:
                _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getTodaySummary, [userId]),
                  ),
                ),
          )
          as _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>> getPurchaseVsSaleStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPurchaseVsSaleStats, [userId]),
            returnValue:
                _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getPurchaseVsSaleStats, [userId]),
                  ),
                ),
          )
          as _i7.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.RepositoryResult<void>> deleteBill(
    String? billId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [billId, userId]),
            returnValue: _i7.Future<_i4.RepositoryResult<void>>.value(
              _FakeRepositoryResult_4<void>(
                this,
                Invocation.method(#deleteBill, [billId, userId]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<void>>);
}

/// A class which mocks [CustomersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomersRepository extends _i1.Mock
    implements _i9.CustomersRepository {
  MockCustomersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i3.SyncManager get syncManager =>
      (super.noSuchMethod(
            Invocation.getter(#syncManager),
            returnValue: _FakeSyncManager_1(
              this,
              Invocation.getter(#syncManager),
            ),
          )
          as _i3.SyncManager);

  @override
  _i4.ErrorHandler get errorHandler =>
      (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: _FakeErrorHandler_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          )
          as _i4.ErrorHandler);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.Customer>> createCustomer({
    required String? userId,
    required String? name,
    String? phone,
    String? email,
    String? address,
    String? gstin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomer, [], {
              #userId: userId,
              #name: name,
              #phone: phone,
              #email: email,
              #address: address,
              #gstin: gstin,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.Customer>>.value(
              _FakeRepositoryResult_4<_i9.Customer>(
                this,
                Invocation.method(#createCustomer, [], {
                  #userId: userId,
                  #name: name,
                  #phone: phone,
                  #email: email,
                  #address: address,
                  #gstin: gstin,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.Customer>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.Customer?>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.Customer?>>.value(
              _FakeRepositoryResult_4<_i9.Customer?>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.Customer?>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.Customer?>> getByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#getByPhone, [phone]),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.Customer?>>.value(
              _FakeRepositoryResult_4<_i9.Customer?>(
                this,
                Invocation.method(#getByPhone, [phone]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.Customer?>>);

  @override
  _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>> getAll({
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#userId: userId}),
            returnValue:
                _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>.value(
                  _FakeRepositoryResult_4<List<_i9.Customer>>(
                    this,
                    Invocation.method(#getAll, [], {#userId: userId}),
                  ),
                ),
          )
          as _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>);

  @override
  _i7.Stream<List<_i9.Customer>> watchAll({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {#userId: userId}),
            returnValue: _i7.Stream<List<_i9.Customer>>.empty(),
          )
          as _i7.Stream<List<_i9.Customer>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.Customer>> updateCustomer(
    _i9.Customer? customer, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [customer], {#userId: userId}),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.Customer>>.value(
              _FakeRepositoryResult_4<_i9.Customer>(
                this,
                Invocation.method(
                  #updateCustomer,
                  [customer],
                  {#userId: userId},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.Customer>>);

  @override
  _i7.Future<_i4.RepositoryResult<bool>> deleteCustomer(
    String? id, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomer, [id], {#userId: userId}),
            returnValue: _i7.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#deleteCustomer, [id], {#userId: userId}),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<bool>>);

  @override
  _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>> getCustomersWithDues({
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersWithDues, [], {#userId: userId}),
            returnValue:
                _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>.value(
                  _FakeRepositoryResult_4<List<_i9.Customer>>(
                    this,
                    Invocation.method(#getCustomersWithDues, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.Customer>> recordPayment({
    required String? customerId,
    required double? amount,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPayment, [], {
              #customerId: customerId,
              #amount: amount,
              #userId: userId,
            }),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.Customer>>.value(
              _FakeRepositoryResult_4<_i9.Customer>(
                this,
                Invocation.method(#recordPayment, [], {
                  #customerId: customerId,
                  #amount: amount,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.Customer>>);

  @override
  _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>> search(
    String? query, {
    required String? userId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [query],
              {#userId: userId, #limit: limit},
            ),
            returnValue:
                _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>.value(
                  _FakeRepositoryResult_4<List<_i9.Customer>>(
                    this,
                    Invocation.method(
                      #search,
                      [query],
                      {#userId: userId, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.RepositoryResult<List<_i9.Customer>>>);

  @override
  _i7.Future<_i4.RepositoryResult<_i9.TrustScore>> calculateTrustScore(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTrustScore, [customerId]),
            returnValue: _i7.Future<_i4.RepositoryResult<_i9.TrustScore>>.value(
              _FakeRepositoryResult_4<_i9.TrustScore>(
                this,
                Invocation.method(#calculateTrustScore, [customerId]),
              ),
            ),
          )
          as _i7.Future<_i4.RepositoryResult<_i9.TrustScore>>);
}

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i3.SyncManager {
  MockSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i11.SyncConflict> get onConflict =>
      (super.noSuchMethod(
            Invocation.getter(#onConflict),
            returnValue: _i7.Stream<_i11.SyncConflict>.empty(),
          )
          as _i7.Stream<_i11.SyncConflict>);

  @override
  _i7.Stream<_i3.SyncHealthMetrics> get syncStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStatusStream),
            returnValue: _i7.Stream<_i3.SyncHealthMetrics>.empty(),
          )
          as _i7.Stream<_i3.SyncHealthMetrics>);

  @override
  _i7.Stream<_i12.SyncResult> get syncEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncEventStream),
            returnValue: _i7.Stream<_i12.SyncResult>.empty(),
          )
          as _i7.Stream<_i12.SyncResult>);

  @override
  _i7.Future<void> initialize({
    required Object? localOperations,
    _i3.SyncManagerConfig? config,
    dynamic firestore,
    dynamic storage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #localOperations: localOperations,
              #config: config,
              #firestore: firestore,
              #storage: storage,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void startSync() => super.noSuchMethod(
    Invocation.method(#startSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSync() => super.noSuchMethod(
    Invocation.method(#stopSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String> enqueue(_i13.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [item]),
            returnValue: _i7.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#enqueue, [item]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<String>> enqueueMultiStep(
    _i13.MultiStepOperation? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueMultiStep, [operation]),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> forceSyncAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceSyncAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resolveConflict(
    _i11.SyncConflict? conflict,
    Map<String, dynamic>? resolution,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflict, [conflict, resolution]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> restoreFullData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFullData, [userId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.SyncHealthMetrics> getHealthMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthMetrics, []),
            returnValue: _i7.Future<_i3.SyncHealthMetrics>.value(
              _FakeSyncHealthMetrics_5(
                this,
                Invocation.method(#getHealthMetrics, []),
              ),
            ),
          )
          as _i7.Future<_i3.SyncHealthMetrics>);
}
