// ============================================================================
// LOG_SCRUBBER — strip secrets, keys, and license keys from log output
// ============================================================================
// Feature: offline-license-activation (Task 18.1 — Security_Layer)
//
// Requirement 17.10: "THE Security_Layer SHALL exclude secrets and license keys
// from all log output." This is the Dart-side counterpart of the packaged
// backend's `logger.ts` scrubber, and it reuses the SAME `maskKey` pattern so a
// value is masked identically wherever it surfaces.
//
// The scrubber is applied at the Dart logging chokepoints (LoggerService and
// AppLogger), so callers do not have to remember to mask values themselves: any
// license key, JWT, or secret-looking token that lands in a log message is
// reduced to a short, non-reversible prefix before it is written.
//
// What it catches:
//   * License keys in the existing DKX-/DKNX- formats (machine-bound activation
//     keys generated by the License_Server).
//   * RS256/JWT tokens (three base64url segments separated by dots), e.g. the
//     License_Token and the local-auth JWT.
//   * `key: value` / `key=value` pairs whose key name looks sensitive
//     (password, secret, token, authorization, apikey, fingerprintHash, …).
//
// PURE DART: no Flutter imports, so it is reusable from the service layer and
// from tests.
//
// Author: DukanX Engineering
// ============================================================================

/// Centralised log-output scrubber for the offline Security_Layer (Req 17.10).
class LogScrubber {
  LogScrubber._();

  /// Names that mark a value as sensitive when they appear as a `key: value`
  /// or `key=value` pair in a log message. Mirrors the packaged backend's
  /// `SENSITIVE_KEY_PATTERN` in `logger.ts`.
  static final RegExp _sensitiveKeyValue = RegExp(
    r'\b(password|passwd|secret|token|authorization|auth|apikey|api[_-]?key|'
    r'license[_-]?key|licensekey|fingerprint[_-]?hash|fingerprinthash|'
    r'private[_-]?key|privatekey|pin|otp)\b'
    r'(\s*[:=]\s*)'
    r'("?)([^\s",}]+)',
    caseSensitive: false,
  );

  /// License keys in the existing DKX-/DKNX- formats (e.g. `DKX-PRO-AB12CD34EF`
  /// or `DKNX-AAAA-BBBB-CCCC`). Matched case-insensitively and masked wherever
  /// they appear in free text.
  static final RegExp _licenseKey = RegExp(
    r'\bDK[A-Z0-9]?X-[A-Z0-9]{3,}(?:-[A-Z0-9]{2,})*',
    caseSensitive: false,
  );

  /// JWT / RS256 tokens: three base64url segments separated by dots. Covers the
  /// License_Token and the local-auth JWT so a stray token in a message never
  /// reaches the log verbatim.
  static final RegExp _jwt = RegExp(
    r'\b[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b',
  );

  /// Masks a single secret/license value, keeping only a short, non-reversible
  /// prefix. Identical contract to the backend `maskKey` so a value is reduced
  /// the same way on both sides of the stack.
  static String maskKey(String value) {
    if (value.isEmpty) return '';
    if (value.length <= 4) return '****';
    return '${value.substring(0, 4)}****';
  }

  /// Returns [message] with every license key, JWT, and sensitive `key: value`
  /// pair masked. Safe to call on any string; returns it unchanged when nothing
  /// sensitive is present.
  static String scrub(String message) {
    if (message.isEmpty) return message;

    var out = message;

    // 1. Sensitive key/value pairs — preserve the key + separator + optional
    //    opening quote, mask only the value.
    out = out.replaceAllMapped(_sensitiveKeyValue, (m) {
      final key = m.group(1);
      final sep = m.group(2);
      final quote = m.group(3) ?? '';
      final value = m.group(4) ?? '';
      return '$key$sep$quote${maskKey(value)}';
    });

    // 2. JWT/RS256 tokens anywhere in the text.
    out = out.replaceAllMapped(_jwt, (m) => maskKey(m.group(0)!));

    // 3. DKX-/DKNX- license keys anywhere in the text.
    out = out.replaceAllMapped(_licenseKey, (m) => maskKey(m.group(0)!));

    return out;
  }
}
