import 'dart:async';
import 'dart:developer' as developer;

import 'package:dukanx/core/api/api_client.dart';
import 'package:dukanx/core/di/service_locator.dart';

import '../../../models/bill.dart';
import 'local_storage_service.dart';

/// Keeps local Hive cache and backend API in sync so bills remain editable offline.
class BillService {
  BillService({LocalStorageService? localStorage})
    : _localStorage = localStorage ?? LocalStorageService();

  final LocalStorageService _localStorage;
  static ApiClient get _api => sl<ApiClient>();

  /// Watch bills stream. Tenant context is extracted from JWT by backend.
  Stream<List<Bill>> watchBills({
    @Deprecated('ownerId is no longer used, extracted from JWT') String? ownerId,
    String? customerId,
    String? businessId,
  }) {

    final controller = StreamController<List<Bill>>.broadcast();
    
    // First yield whatever we have in the local cache
    controller.add(
      _filterCachedBills(
        ownerId: ownerId ?? '',
        customerId: customerId,
        businessId: businessId,
      ),
    );

    // Then asynchronously fetch from backend
    _fetchAndCacheBills(
      customerId: customerId, 
      businessId: businessId,
    ).then((bills) {
      if (!controller.isClosed) {
        controller.add(
          _filterCachedBills(
            ownerId: ownerId ?? '',
            customerId: customerId,
            businessId: businessId,
            source: bills,
          ),
        );
      }
    }).catchError((error, stack) {
      developer.log(
        'Bill stream api error: $error',
        name: 'BillService',
        error: error,
        stackTrace: stack,
      );
      if (!controller.isClosed) {
        // Yield cache again just to be safe
        controller.add(
          _filterCachedBills(
            ownerId: ownerId ?? '',
            customerId: customerId,
            businessId: businessId,
          ),
        );
      }
    }).whenComplete(() {
      // SY-03 FIX: Close the controller after fetch completes to prevent memory leak
      if (!controller.isClosed) {
        controller.close();
      }
    });

    return controller.stream;
  }

  Future<List<Bill>> _fetchAndCacheBills({
    String? customerId,
    String? businessId,
  }) async {
    final queryParams = <String, String>{};
    if (customerId != null && customerId.isNotEmpty) {
      queryParams['customerId'] = customerId;
    }
    if (businessId != null && businessId.isNotEmpty) {
      queryParams['businessId'] = businessId;
    }

    final response = await _api.get('/api/v1/bills', queryParameters: queryParams);
    
    if (response.isSuccess && response.data != null) {
      final list = response.data!['items'] as List<dynamic>? ?? response.data! as List<dynamic>? ?? [];
      final bills = list.map((b) => Bill.fromMap(b['id'] ?? b['_id'], b)).toList();
      
      // Update local storage
      await _localStorage.replaceBills(bills);
      return bills;
    } else {
      throw Exception('Failed to fetch bills from API');
    }
  }

  /// Fetch bills. Tenant context is extracted from JWT by backend.
  Future<List<Bill>> fetchBills({
    @Deprecated('ownerId is no longer used, extracted from JWT') String? ownerId,
    String? customerId,
    String? businessId,
    bool refresh = false,
  }) async {

    if (!refresh) {
      final cached = _filterCachedBills(
        ownerId: ownerId ?? '',
        customerId: customerId,
        businessId: businessId,
      );
      if (cached.isNotEmpty) return cached;
    }
    
    try {
      return await _fetchAndCacheBills(
        customerId: customerId,
        businessId: businessId,
      );
    } catch (e, stack) {
      developer.log(
        'fetchBills fallback to cache: $e',
        name: 'BillService',
        error: e,
        stackTrace: stack,
      );
      final cached = _filterCachedBills(
        ownerId: ownerId ?? '',
        customerId: customerId,
        businessId: businessId,
      );
      if (cached.isNotEmpty) return cached;
      rethrow;
    }
  }

  /// Save a new bill. [bill.id] MUST be pre-generated by the caller (UUID).
  Future<Bill> saveBill(Bill bill, {@Deprecated('ownerId is extracted from JWT') String? ownerId}) async {
    if (bill.id.isEmpty) {
      throw ArgumentError(
        'bill.id must be pre-generated (UUID) for idempotency. '
        'Generate with const Uuid().v4() before calling saveBill.',
      );
    }

    final sanitized = bill.copyWith(
          ownerId: bill.ownerId, // keep existing or let server overwrite
          date: bill.date.toLocal(),
        )
        .sanitized();

    await _localStorage.saveBill(sanitized);
    await _localStorage.setSyncStatus('bill', sanitized.id, false);

    try {
      await _api.post('/api/v1/bills', body: sanitized.toMap());
      await _localStorage.setSyncStatus('bill', sanitized.id, true);
      return sanitized;
    } catch (e, stack) {
      developer.log(
        'Bill save offline, will retry sync: $e',
        name: 'BillService',
        error: e,
        stackTrace: stack,
      );
      throw Exception('Bill saved locally. Sync pending. (${e.toString()})');
    }
  }

  Future<void> updateBill(Bill bill) async {
    if (bill.id.isEmpty) {
      throw ArgumentError('Bill ID is required for update');
    }
    final sanitized = bill.sanitized();
    
    await _localStorage.updateBill(sanitized);
    await _localStorage.setSyncStatus('bill', sanitized.id, false);
    
    try {
      await _api.put('/api/v1/bills/${sanitized.id}', body: sanitized.toMap());
      await _localStorage.setSyncStatus('bill', sanitized.id, true);
    } catch (e, stack) {
      developer.log(
        'Bill update failed: $e',
        name: 'BillService',
        error: e,
        stackTrace: stack,
      );
      throw Exception('Unable to sync bill. ${e.toString()}');
    }
  }

  Future<void> deleteBill(String billId) async {
    await _localStorage.deleteBill(billId);
    await _localStorage.setSyncStatus('bill', billId, false);
    
    try {
      await _api.delete('/api/v1/bills/$billId');
      await _localStorage.setSyncStatus('bill', billId, true);
    } catch (e, stack) {
      developer.log(
        'Bill delete failed: $e',
        name: 'BillService',
        error: e,
        stackTrace: stack,
      );
      throw Exception('Unable to delete bill online. ${e.toString()}');
    }
  }

  Future<void> syncPendingBills() async {
    final unsynced = _localStorage
        .getUnsyncedItems()
        .where((item) => item['dataType'] == 'bill' && item['itemId'] != null)
        .toList();
        
    if (unsynced.isEmpty) return;

    final cache = _localStorage.getAllBills();
    for (final entry in unsynced) {
      final billId = entry['itemId'] as String;
      final bill = cache.firstWhere(
        (b) => b.id == billId,
        orElse: () => Bill.empty(),
      );
      if (bill.id.isEmpty) continue;
      
      try {
        await _api.put('/api/v1/bills/${bill.id}', body: bill.toMap());
        await _localStorage.setSyncStatus('bill', bill.id, true);
      } catch (e, stack) {
        developer.log(
          'Retry bill sync failed for ${bill.id}: $e',
          name: 'BillService',
          error: e,
          stackTrace: stack,
        );
      }
    }
  }

  List<Bill> _filterCachedBills({
    String? ownerId,
    String? customerId,
    String? businessId,
    List<Bill>? source,
  }) {
    final bills = source ?? _localStorage.getAllBills();
    return bills.where((bill) {
      final ownerMatches = ownerId == null || ownerId.isEmpty
          ? true
          : bill.ownerId == ownerId;
      final customerMatches = customerId == null || customerId.isEmpty
          ? true
          : bill.customerId == customerId;
      final businessMatches = businessId == null || businessId.isEmpty
          ? true
          : bill.businessId == businessId;
      return ownerMatches && customerMatches && businessMatches;
    }).toList();
  }
}
