// Mocks generated by Mockito 5.4.6 from annotations
// in dukanx/test/features/inventory/services/batch_allocation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dukanx/core/database/app_database.dart' as _i4;
import 'package:dukanx/features/inventory/data/product_batch_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductBatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBatchRepository extends _i1.Mock
    implements _i2.ProductBatchRepository {
  MockProductBatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductBatchEntity>> getBatchesForFefo(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchesForFefo, [productId]),
            returnValue: _i3.Future<List<_i4.ProductBatchEntity>>.value(
              <_i4.ProductBatchEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductBatchEntity>>);

  @override
  _i3.Future<List<_i4.ProductBatchEntity>> getAllBatches(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBatches, [productId]),
            returnValue: _i3.Future<List<_i4.ProductBatchEntity>>.value(
              <_i4.ProductBatchEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductBatchEntity>>);

  @override
  _i3.Future<String> createBatch(_i4.ProductBatchesCompanion? batch) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [batch]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createBatch, [batch]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<double> updateBatchStock(String? batchId, double? deltaQty) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatchStock, [batchId, deltaQty]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<_i4.ProductBatchEntity?> getBatchByNumber(
    String? productId,
    String? batchNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchByNumber, [productId, batchNumber]),
            returnValue: _i3.Future<_i4.ProductBatchEntity?>.value(),
          )
          as _i3.Future<_i4.ProductBatchEntity?>);
}
