// Mocks generated by Mockito 5.4.6 from annotations
// in dukanx/test/features/inventory/services/pharmacy_migration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dukanx/core/database/app_database.dart' as _i2;
import 'package:dukanx/core/error/error_handler.dart' as _i4;
import 'package:dukanx/core/repository/products_repository.dart' as _i6;
import 'package:dukanx/core/services/event_dispatcher.dart' as _i5;
import 'package:dukanx/core/sync/sync_manager.dart' as _i3;
import 'package:dukanx/features/inventory/data/product_batch_repository.dart'
    as _i10;
import 'package:dukanx/models/reorder_prediction.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncManager_1 extends _i1.SmartFake implements _i3.SyncManager {
  _FakeSyncManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeErrorHandler_2 extends _i1.SmartFake implements _i4.ErrorHandler {
  _FakeErrorHandler_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventDispatcher_3 extends _i1.SmartFake
    implements _i5.EventDispatcher {
  _FakeEventDispatcher_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRepositoryResult_4<T> extends _i1.SmartFake
    implements _i4.RepositoryResult<T> {
  _FakeRepositoryResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i6.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i3.SyncManager get syncManager =>
      (super.noSuchMethod(
            Invocation.getter(#syncManager),
            returnValue: _FakeSyncManager_1(
              this,
              Invocation.getter(#syncManager),
            ),
          )
          as _i3.SyncManager);

  @override
  _i4.ErrorHandler get errorHandler =>
      (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: _FakeErrorHandler_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          )
          as _i4.ErrorHandler);

  @override
  _i5.EventDispatcher get eventDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#eventDispatcher),
            returnValue: _FakeEventDispatcher_3(
              this,
              Invocation.getter(#eventDispatcher),
            ),
          )
          as _i5.EventDispatcher);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i8.Future<_i4.RepositoryResult<_i6.Product>> createProduct({
    required String? userId,
    required String? name,
    String? sku,
    String? barcode,
    String? category,
    String? unit = 'pcs',
    required double? sellingPrice,
    double? costPrice = 0.0,
    double? taxRate = 0.0,
    double? stockQuantity = 0.0,
    double? lowStockThreshold = 10.0,
    String? size,
    String? color,
    String? brand,
    String? hsnCode,
    List<String>? altBarcodes,
    String? drugSchedule,
    String? groupId,
    Map<String, String>? variantAttributes,
    List<Map<String, dynamic>>? initialBatches,
    List<String>? initialImeis,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [], {
              #userId: userId,
              #name: name,
              #sku: sku,
              #barcode: barcode,
              #category: category,
              #unit: unit,
              #sellingPrice: sellingPrice,
              #costPrice: costPrice,
              #taxRate: taxRate,
              #stockQuantity: stockQuantity,
              #lowStockThreshold: lowStockThreshold,
              #size: size,
              #color: color,
              #brand: brand,
              #hsnCode: hsnCode,
              #altBarcodes: altBarcodes,
              #drugSchedule: drugSchedule,
              #groupId: groupId,
              #variantAttributes: variantAttributes,
              #initialBatches: initialBatches,
              #initialImeis: initialImeis,
            }),
            returnValue: _i8.Future<_i4.RepositoryResult<_i6.Product>>.value(
              _FakeRepositoryResult_4<_i6.Product>(
                this,
                Invocation.method(#createProduct, [], {
                  #userId: userId,
                  #name: name,
                  #sku: sku,
                  #barcode: barcode,
                  #category: category,
                  #unit: unit,
                  #sellingPrice: sellingPrice,
                  #costPrice: costPrice,
                  #taxRate: taxRate,
                  #stockQuantity: stockQuantity,
                  #lowStockThreshold: lowStockThreshold,
                  #size: size,
                  #color: color,
                  #brand: brand,
                  #hsnCode: hsnCode,
                  #altBarcodes: altBarcodes,
                  #drugSchedule: drugSchedule,
                  #groupId: groupId,
                  #variantAttributes: variantAttributes,
                  #initialBatches: initialBatches,
                  #initialImeis: initialImeis,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.RepositoryResult<_i6.Product>>);

  @override
  _i8.Future<_i4.RepositoryResult<_i6.Product?>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i8.Future<_i4.RepositoryResult<_i6.Product?>>.value(
              _FakeRepositoryResult_4<_i6.Product?>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i8.Future<_i4.RepositoryResult<_i6.Product?>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i6.Product>>> getAll({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#userId: userId}),
            returnValue:
                _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i6.Product>>(
                    this,
                    Invocation.method(#getAll, [], {#userId: userId}),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>);

  @override
  _i8.Stream<List<_i6.Product>> watchAll({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {#userId: userId}),
            returnValue: _i8.Stream<List<_i6.Product>>.empty(),
          )
          as _i8.Stream<List<_i6.Product>>);

  @override
  _i8.Stream<List<String>> watchUniqueCategories({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchUniqueCategories, [], {#userId: userId}),
            returnValue: _i8.Stream<List<String>>.empty(),
          )
          as _i8.Stream<List<String>>);

  @override
  _i8.Future<_i4.RepositoryResult<_i6.Product>> updateProduct(
    _i6.Product? product, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product], {#userId: userId}),
            returnValue: _i8.Future<_i4.RepositoryResult<_i6.Product>>.value(
              _FakeRepositoryResult_4<_i6.Product>(
                this,
                Invocation.method(#updateProduct, [product], {#userId: userId}),
              ),
            ),
          )
          as _i8.Future<_i4.RepositoryResult<_i6.Product>>);

  @override
  _i8.Future<_i4.RepositoryResult<bool>> deleteProduct(
    String? id, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id], {#userId: userId}),
            returnValue: _i8.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#deleteProduct, [id], {#userId: userId}),
              ),
            ),
          )
          as _i8.Future<_i4.RepositoryResult<bool>>);

  @override
  _i8.Future<_i4.RepositoryResult<_i6.Product>> adjustStock({
    required String? productId,
    required double? quantity,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #quantity: quantity,
              #userId: userId,
            }),
            returnValue: _i8.Future<_i4.RepositoryResult<_i6.Product>>.value(
              _FakeRepositoryResult_4<_i6.Product>(
                this,
                Invocation.method(#adjustStock, [], {
                  #productId: productId,
                  #quantity: quantity,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.RepositoryResult<_i6.Product>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i6.Product>>> getLowStockProducts({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLowStockProducts, [], {#userId: userId}),
            returnValue:
                _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i6.Product>>(
                    this,
                    Invocation.method(#getLowStockProducts, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i6.Product>>> getDeadStock({
    required String? userId,
    required int? daysUnsold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDeadStock, [], {
              #userId: userId,
              #daysUnsold: daysUnsold,
            }),
            returnValue:
                _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i6.Product>>(
                    this,
                    Invocation.method(#getDeadStock, [], {
                      #userId: userId,
                      #daysUnsold: daysUnsold,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i9.ReorderPrediction>>>
  getSmartReorderSuggestions({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSmartReorderSuggestions, [], {
              #userId: userId,
            }),
            returnValue:
                _i8.Future<
                  _i4.RepositoryResult<List<_i9.ReorderPrediction>>
                >.value(
                  _FakeRepositoryResult_4<List<_i9.ReorderPrediction>>(
                    this,
                    Invocation.method(#getSmartReorderSuggestions, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i9.ReorderPrediction>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i6.Product>>> search(
    String? query, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#userId: userId}),
            returnValue:
                _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i6.Product>>(
                    this,
                    Invocation.method(#search, [query], {#userId: userId}),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i6.Product>>>);

  @override
  _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>> getStockStatusSummary(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStockStatusSummary, [userId]),
            returnValue:
                _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getStockStatusSummary, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>> getSalesPerformance(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesPerformance, [userId]),
            returnValue:
                _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getSalesPerformance, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>
  getBatchesForProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchesForProduct, [productId]),
            returnValue:
                _i8.Future<
                  _i4.RepositoryResult<List<_i2.ProductBatchEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.ProductBatchEntity>>(
                    this,
                    Invocation.method(#getBatchesForProduct, [productId]),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>> getAllBatches(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBatches, [userId]),
            returnValue:
                _i8.Future<
                  _i4.RepositoryResult<List<_i2.ProductBatchEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.ProductBatchEntity>>(
                    this,
                    Invocation.method(#getAllBatches, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>);

  @override
  _i8.Future<_i4.RepositoryResult<List<_i2.StockMovementEntity>>> getDamageLogs(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDamageLogs, [userId]),
            returnValue:
                _i8.Future<
                  _i4.RepositoryResult<List<_i2.StockMovementEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.StockMovementEntity>>(
                    this,
                    Invocation.method(#getDamageLogs, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.RepositoryResult<List<_i2.StockMovementEntity>>>);
}

/// A class which mocks [ProductBatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBatchRepository extends _i1.Mock
    implements _i10.ProductBatchRepository {
  MockProductBatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.ProductBatchEntity>> getBatchesForFefo(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchesForFefo, [productId]),
            returnValue: _i8.Future<List<_i2.ProductBatchEntity>>.value(
              <_i2.ProductBatchEntity>[],
            ),
          )
          as _i8.Future<List<_i2.ProductBatchEntity>>);

  @override
  _i8.Future<List<_i2.ProductBatchEntity>> getAllBatches(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBatches, [productId]),
            returnValue: _i8.Future<List<_i2.ProductBatchEntity>>.value(
              <_i2.ProductBatchEntity>[],
            ),
          )
          as _i8.Future<List<_i2.ProductBatchEntity>>);

  @override
  _i8.Future<String> createBatch(_i2.ProductBatchesCompanion? batch) =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, [batch]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createBatch, [batch]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<double> updateBatchStock(String? batchId, double? deltaQty) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatchStock, [batchId, deltaQty]),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<_i2.ProductBatchEntity?> getBatchByNumber(
    String? productId,
    String? batchNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchByNumber, [productId, batchNumber]),
            returnValue: _i8.Future<_i2.ProductBatchEntity?>.value(),
          )
          as _i8.Future<_i2.ProductBatchEntity?>);
}
