/// Warranty Claim Service
/// Business logic for warranty claim management
library;

import 'package:dukanx/core/database/app_database.dart';
import '../data/repositories/warranty_claim_repository.dart';
import '../data/repositories/imei_serial_repository.dart';
import '../models/warranty_claim.dart';

/// Service for managing warranty claims
class WarrantyClaimService {
  final WarrantyClaimRepository _claimRepository;
  final IMEISerialRepository _imeiRepository;

  WarrantyClaimService(AppDatabase db)
    : _claimRepository = WarrantyClaimRepository(db),
      _imeiRepository = IMEISerialRepository(db);

  // ===========================================================================
  // CLAIM CREATION
  // ===========================================================================

  /// File a new warranty claim
  ///
  /// Automatically verifies warranty status based on IMEI record
  Future<WarrantyClaim> fileClaim({
    required String userId,
    required String originalBillId,
    String? originalInvoiceNumber,
    String? originalSaleDate,
    required String productId,
    required String productName,
    String? brand,
    String? model,
    required String imeiOrSerial,
    String? color,
    String? storage,
    String? customerId,
    required String customerName,
    required String customerPhone,
    String? customerEmail,
    required String issueDescription,
    List<String> symptoms = const [],
    List<String> issuePhotos = const [],
  }) async {
    // Verify warranty status
    final imeiRecord = await _imeiRepository.getByNumber(userId, imeiOrSerial);

    bool isUnderWarranty = false;
    DateTime? warrantyStartDate;
    DateTime? warrantyEndDate;
    int warrantyPeriodMonths = 0;
    String? verificationNotes;

    if (imeiRecord != null) {
      isUnderWarranty = imeiRecord.isWarrantyActive;
      warrantyStartDate = imeiRecord.warrantyStartDate;
      warrantyEndDate = imeiRecord.warrantyEndDate;
      warrantyPeriodMonths = imeiRecord.warrantyMonths;

      if (isUnderWarranty) {
        final daysRemaining =
            warrantyEndDate?.difference(DateTime.now()).inDays ?? 0;
        verificationNotes = 'Warranty verified: $daysRemaining days remaining';
      } else {
        verificationNotes =
            'Device out of warranty. Expired on ${warrantyEndDate?.toIso8601String()}';
      }
    } else {
      verificationNotes =
          'IMEI/Serial not found in system. Manual verification required.';
    }

    final now = DateTime.now();

    final claim = WarrantyClaim(
      id: '',
      userId: userId,
      claimNumber: '', // Auto-generated by repository
      originalBillId: originalBillId,
      originalInvoiceNumber: originalInvoiceNumber,
      originalSaleDate: originalSaleDate,
      productId: productId,
      productName: productName,
      brand: brand,
      model: model,
      imeiOrSerial: imeiOrSerial,
      color: color,
      storage: storage,
      customerId: customerId,
      customerName: customerName,
      customerPhone: customerPhone,
      customerEmail: customerEmail,
      issueDescription: issueDescription,
      symptoms: symptoms,
      issuePhotos: issuePhotos,
      warrantyStartDate: warrantyStartDate,
      warrantyEndDate: warrantyEndDate,
      warrantyPeriodMonths: warrantyPeriodMonths,
      isUnderWarranty: isUnderWarranty,
      warrantyVerificationNotes: verificationNotes,
      status: WarrantyClaimStatus.filed,
      filedAt: now,
      createdAt: now,
      updatedAt: now,
    );

    final claimId = await _claimRepository.createClaim(claim);
    return claim.copyWith(id: claimId);
  }

  // ===========================================================================
  // CLAIM RETRIEVAL
  // ===========================================================================

  /// Get claim by ID
  Future<WarrantyClaim?> getClaimById(
    String id, {
    required String userId,
  }) async {
    return _claimRepository.getClaimById(id, userId: userId);
  }

  /// Get claim by number
  Future<WarrantyClaim?> getClaimByNumber(
    String userId,
    String claimNumber,
  ) async {
    return _claimRepository.getClaimByNumber(userId, claimNumber);
  }

  /// Get all claims for user
  Future<List<WarrantyClaim>> getAllClaims(String userId) async {
    return _claimRepository.getAllClaims(userId);
  }

  /// Get active claims (not closed/rejected)
  Future<List<WarrantyClaim>> getActiveClaims(String userId) async {
    return _claimRepository.getActiveClaims(userId);
  }

  /// Get claims by status
  Future<List<WarrantyClaim>> getClaimsByStatus(
    String userId,
    WarrantyClaimStatus status,
  ) async {
    return _claimRepository.getClaimsByStatus(userId, status);
  }

  /// Get claims for a customer
  Future<List<WarrantyClaim>> getCustomerClaims(
    String userId,
    String customerId,
  ) async {
    return _claimRepository.getClaimsByCustomer(userId, customerId);
  }

  /// Get claims for a specific device
  Future<List<WarrantyClaim>> getDeviceClaims(
    String userId,
    String imeiOrSerial,
  ) async {
    return _claimRepository.getClaimsByIMEI(userId, imeiOrSerial);
  }

  /// Get claims statistics
  Future<Map<String, dynamic>> getClaimsStats(String userId) async {
    return _claimRepository.getClaimsStats(userId);
  }

  // ===========================================================================
  // CLAIM WORKFLOW
  // ===========================================================================

  /// Review claim and decide on warranty coverage
  Future<void> reviewClaim({
    required String claimId,
    required String userId,
    required bool isApproved,
    required String reviewedByUserId,
    required String reviewedByName,
    String? notes,
    RejectionReason? rejectionReason,
  }) async {
    if (isApproved) {
      await _claimRepository.updateStatus(
        claimId,
        WarrantyClaimStatus.approved,
        userId: userId,
        reviewedByUserId: reviewedByUserId,
        reviewedByName: reviewedByName,
        notes: notes ?? 'Claim approved for warranty coverage',
      );
    } else {
      if (rejectionReason == null) {
        throw ArgumentError('Rejection reason required when not approved');
      }
      await _claimRepository.rejectClaim(
        claimId,
        userId: userId,
        reason: rejectionReason,
        notes: notes ?? 'Claim rejected',
        reviewedByUserId: reviewedByUserId,
        reviewedByName: reviewedByName,
      );
    }
  }

  /// Assign technician to claim
  Future<void> assignTechnician({
    required String claimId,
    required String userId,
    required String technicianId,
    required String technicianName,
  }) async {
    await _claimRepository.assignTechnician(
      claimId,
      userId: userId,
      technicianId: technicianId,
      technicianName: technicianName,
    );

    // Also update status to indicate technician assigned
    final claim = await _claimRepository.getClaimById(claimId, userId: userId);
    if (claim != null && claim.status == WarrantyClaimStatus.approved) {
      await _claimRepository.updateStatus(
        claimId,
        WarrantyClaimStatus.inRepair,
        userId: userId,
      );
    }
  }

  /// Order parts for claim
  Future<void> orderParts(String claimId, {required String userId}) async {
    await _claimRepository.updateStatus(
      claimId,
      WarrantyClaimStatus.partsOrdered,
      userId: userId,
    );
  }

  /// Start repair (after parts arrive)
  Future<void> startRepair(String claimId, {required String userId}) async {
    await _claimRepository.updateStatus(
      claimId,
      WarrantyClaimStatus.inRepair,
      userId: userId,
    );
  }

  /// Complete repair
  Future<void> completeRepair({
    required String claimId,
    required String userId,
    required String workDone,
    List<WarrantyClaimPart>? partsReplaced,
    double? laborCost,
    String? resolutionNotes,
  }) async {
    // Add parts if provided
    if (partsReplaced != null && partsReplaced.isNotEmpty) {
      await _claimRepository.addPartsReplaced(
        claimId,
        partsReplaced,
        userId: userId,
        laborCost: laborCost,
      );
    } else if (laborCost != null) {
      // Just update labor cost
      final claim = await _claimRepository.getClaimById(
        claimId,
        userId: userId,
      );
      if (claim != null) {
        final totalClaimCost = claim.totalPartsCost + laborCost;
        await _claimRepository.addPartsReplaced(
          claimId,
          [],
          userId: userId,
          laborCost: laborCost,
        );
      }
    }

    // Update work done
    await _claimRepository.updateResolution(
      claimId,
      userId: userId,
      workDone: workDone,
      resolutionNotes: resolutionNotes,
    );

    // Mark completed
    await _claimRepository.updateStatus(
      claimId,
      WarrantyClaimStatus.completed,
      userId: userId,
    );
  }

  /// Close claim (device delivered to customer)
  Future<void> closeClaim({
    required String claimId,
    required String userId,
    String? notes,
  }) async {
    await _claimRepository.updateStatus(
      claimId,
      WarrantyClaimStatus.closed,
      userId: userId,
      notes: notes ?? 'Device delivered to customer',
    );
  }

  /// Link claim to service job (if repair done via service job flow)
  Future<void> linkToServiceJob(
    String claimId,
    String serviceJobId, {
    required String userId,
  }) async {
    await _claimRepository.linkServiceJob(
      claimId,
      serviceJobId,
      userId: userId,
    );
  }

  // ===========================================================================
  // FINANCIAL TRACKING
  // ===========================================================================

  /// Record reimbursement from supplier/manufacturer
  Future<void> recordReimbursement({
    required String claimId,
    required String userId,
    required double amount,
    String? reference,
  }) async {
    await _claimRepository.updateReimbursement(
      claimId,
      userId: userId,
      isReimbursed: true,
      amount: amount,
      reference: reference,
    );
  }

  /// Get total warranty costs for P&L reporting
  Future<Map<String, dynamic>> getWarrantyCostsForPeriod(
    String userId,
    DateTime startDate,
    DateTime endDate,
  ) async {
    final allClaims = await _claimRepository.getAllClaims(userId);

    final claimsInPeriod = allClaims.where((c) {
      return c.filedAt.isAfter(startDate) &&
          c.filedAt.isBefore(endDate.add(const Duration(days: 1)));
    }).toList();

    double totalCosts = 0;
    double totalReimbursed = 0;
    int approvedClaims = 0;
    int rejectedClaims = 0;

    for (final claim in claimsInPeriod) {
      if (claim.status != WarrantyClaimStatus.rejected) {
        totalCosts += claim.totalClaimCost;
        approvedClaims++;
      } else {
        rejectedClaims++;
      }

      if (claim.isReimbursedBySupplier) {
        totalReimbursed += claim.reimbursementAmount ?? 0;
      }
    }

    return {
      'totalClaims': claimsInPeriod.length,
      'approvedClaims': approvedClaims,
      'rejectedClaims': rejectedClaims,
      'totalCosts': totalCosts,
      'totalReimbursed': totalReimbursed,
      'netWarrantyExpense': totalCosts - totalReimbursed,
      'period':
          '${startDate.toIso8601String()} to ${endDate.toIso8601String()}',
    };
  }

  // ===========================================================================
  // STREAMS
  // ===========================================================================

  /// Watch all claims as stream
  Stream<List<WarrantyClaim>> watchAllClaims(String userId) {
    return _claimRepository.watchAllClaims(userId);
  }

  /// Watch active claims as stream
  Stream<List<WarrantyClaim>> watchActiveClaims(String userId) {
    return _claimRepository.watchActiveClaims(userId);
  }

  // ===========================================================================
  // HELPER METHODS
  // ===========================================================================

  /// Get warranty status summary for a device
  Future<Map<String, dynamic>> getDeviceWarrantySummary(
    String userId,
    String imeiOrSerial,
  ) async {
    final imeiRecord = await _imeiRepository.getByNumber(userId, imeiOrSerial);
    final claims = await _claimRepository.getClaimsByIMEI(userId, imeiOrSerial);

    if (imeiRecord == null) {
      return {'deviceFound': false, 'message': 'Device not found in system'};
    }

    final activeClaims = claims.where((c) => c.isActive).toList();
    final completedClaims = claims
        .where(
          (c) =>
              c.status == WarrantyClaimStatus.completed ||
              c.status == WarrantyClaimStatus.closed,
        )
        .toList();

    return {
      'deviceFound': true,
      'productName': imeiRecord.productName,
      'brand': imeiRecord.brand,
      'model': imeiRecord.model,
      'isUnderWarranty': imeiRecord.isWarrantyActive,
      'warrantyStartDate': imeiRecord.warrantyStartDate?.toIso8601String(),
      'warrantyEndDate': imeiRecord.warrantyEndDate?.toIso8601String(),
      'daysRemaining': imeiRecord.warrantyEndDate != null
          ? imeiRecord.warrantyEndDate!.difference(DateTime.now()).inDays
          : 0,
      'totalClaimsHistory': claims.length,
      'activeClaims': activeClaims.length,
      'completedClaims': completedClaims.length,
      'canFileNewClaim': imeiRecord.isWarrantyActive && activeClaims.isEmpty,
      'message': imeiRecord.isWarrantyActive
          ? 'Device under warranty. ${activeClaims.isNotEmpty ? "Active claim exists." : "Eligible for new claim."}'
          : 'Device out of warranty.',
    };
  }
}
