import 'dart:convert';

import 'package:drift/drift.dart';

import '../../../core/database/app_database.dart';
import '../../../core/di/service_locator.dart';
import '../../../core/session/session_manager.dart';
import '../domain/moq_validator.dart';
import '../domain/rate_list.dart';
import '../domain/rid_generator.dart';
import '../domain/stock_by_location.dart';
import '../domain/transport_details.dart';
import '../domain/transport_validator.dart';
import '../domain/validation_result.dart';
import '../domain/warehouse.dart';
import '../domain/eway_record.dart';
import '../domain/eway_rules.dart';
import 'unresolved_tenant_error.dart';

/// Abstract interface for the tenant-scoped wholesale repository.
///
/// Every method resolves `tenantId` from the authenticated session via
/// [withTenant]. A missing/unresolvable tenant throws [UnresolvedTenantError]
/// and performs no I/O (Requirement 1.5, 1.6, 1.7).
///
/// Money values are integer Paise. IDs follow the RID pattern.
abstract class WholesaleRepository {
  /// Resolves the active Tenant_Id from the authenticated session and passes
  /// it to [op]. If the tenant is null, empty, or otherwise unresolvable,
  /// throws [UnresolvedTenantError] immediately — no I/O is performed.
  ///
  /// All repository methods use this as their entry point to guarantee
  /// tenant scoping on every operation.
  Future<T> withTenant<T>(Future<T> Function(String tenantId) op);

  /// Persists the MOQ (minimum order / case-pack quantity) for [productId],
  /// scoped by the active Tenant_Id.
  ///
  /// [moqValue] must be a positive integer (> 0). Zero, negative, or
  /// non-positive values are rejected with an [ArgumentError] before
  /// any persistence occurs (§14, Requirement 7.7).
  Future<void> saveMoq(String productId, int moqValue);

  /// Persists the unit conversion factor (box→pieces) for [productId],
  /// scoped by the active Tenant_Id.
  ///
  /// [factor] must be a positive integer (> 0). Zero, negative, or
  /// non-positive values are rejected with an [ArgumentError] before
  /// any persistence occurs (§14, Requirement 7.7).
  Future<void> saveUnitConversionFactor(String productId, int factor);

  /// Persists a [TransportDetails] record scoped to the active Tenant_Id
  /// with an RID identifier generated by [DefaultRidGenerator].
  ///
  /// Validates required fields (vehicleNumber, transporterName) before
  /// saving. Rejects an empty required field with a validation error and
  /// persists no incomplete record (Requirement 8.3, 8.5, 8.6, 1.4).
  ///
  /// Returns the persisted [TransportDetails] with the assigned RID id
  /// and resolved tenantId.
  Future<TransportDetails> saveTransport(TransportDetails details);

  /// Persists the credit limit for [partyId], scoped by the active Tenant_Id.
  ///
  /// [limitPaise] is the credit limit in integer Paise (>= 0). A value of 0
  /// means "no limit configured" — the party is always allowed.
  ///
  /// The existing `creditLimit` column is a RealColumn (float, rupees), so
  /// this method converts paise → rupees before persisting:
  /// `creditLimit = limitPaise / 100.0`.
  ///
  /// (§4, §5; Requirement 9.6)
  Future<void> saveCreditLimit(String partyId, int limitPaise);

  /// Returns the count of customers whose outstanding balance is at or above
  /// 80% of their configured credit limit (both > 0), scoped by the active
  /// Tenant_Id.
  ///
  /// This provides the real "customers near limit" count for the wholesale
  /// dashboard alert, replacing the Phase 1 zeroed/hidden fabricated count
  /// (§5, §8; Requirement 9.7).
  Future<int> nearCreditLimitCount();

  /// Persists a [Warehouse] (godown) scoped to the active Tenant_Id.
  ///
  /// Generates an RID for the warehouse. The warehouse name must not be empty.
  /// Returns the persisted [Warehouse] with the assigned RID and tenantId.
  ///
  /// (§2; Requirement 10.2, 10.3)
  Future<Warehouse> saveWarehouse(Warehouse w);

  /// Returns all warehouses for the active tenant.
  ///
  /// (Requirement 10.2)
  Future<List<Warehouse>> getWarehousesForTenant();

  /// Records a stock movement at a specific warehouse location.
  ///
  /// Updates the stock quantity for [productId] at [locationId] by
  /// [quantityDelta]. If the location does not belong to the active tenant,
  /// throws [ForeignTenantMovementError] and persists nothing.
  ///
  /// (§2; Requirement 10.4)
  Future<void> recordStockMovement(
    String locationId,
    String productId,
    int quantityDelta,
  );

  // ==========================================================================
  // Phase 8 — Tiered/Slab Pricing & Party Rate Lists (Requirement 11)
  // ==========================================================================

  /// Persists a [RateList] scoped to the active Tenant_Id with an RID
  /// identifier and all rates in integer Paise.
  ///
  /// The slabs are stored as JSON in a TEXT column for simplicity.
  /// If [rateList.id] is empty, a new RID is generated; otherwise the
  /// existing record is updated (upsert).
  ///
  /// Returns the persisted [RateList] with the assigned/confirmed RID and
  /// tenantId.
  ///
  /// (§3; Requirement 11.3)
  Future<RateList> saveRateList(RateList rateList);

  /// Returns rate lists for the given [productId], optionally filtered by
  /// [partyId].
  ///
  /// If [partyId] is provided, returns only rate lists for that party.
  /// If [partyId] is null, returns all rate lists for the product (both
  /// party-specific and generic).
  ///
  /// (§3; Requirement 11.4)
  Future<List<RateList>> getRateListsForProduct(
    String productId, {
    String? partyId,
  });

  /// Returns all rate lists for the active tenant.
  ///
  /// Used by the rate-list editor screen to display all configured rate lists.
  ///
  /// (§3; Requirement 11.7)
  Future<List<RateList>> getAllRateLists();

  // ==========================================================================
  // Phase 9 — E-Way Bill Records (Requirement 12)
  // ==========================================================================

  /// Persists an [EWayRecord] scoped to the active Tenant_Id with an RID
  /// identifier, money in integer Paise, and — since GSP_Credentials are
  /// unavailable — `ewayNumber: null` and `status: EWayStatus.blocked`.
  ///
  /// Validates the capture fields via [EWayRules.validateCapture] before
  /// persisting. Rejects invalid captures with an [ArgumentError].
  ///
  /// NEVER fabricates, mocks, or simulates an e-Way number.
  ///
  /// (§19; Requirement 12.7)
  Future<EWayRecord> saveEWay(EWayRecord record);
}

/// Concrete implementation of [WholesaleRepository].
///
/// Resolves the tenant from the [SessionManager] registered in the service
/// locator. The resolution uses `currentBusinessId ?? userId` — the same
/// pattern the rest of DukanX uses for multi-business support — and never
/// falls back to a hardcoded literal such as `'SYSTEM'`.
class WholesaleRepositoryImpl implements WholesaleRepository {
  /// The session manager used to resolve the active tenant.
  /// Injected via constructor for testability; defaults to the DI-registered
  /// [SessionManager] singleton.
  final SessionManager _sessionManager;

  /// The Drift database instance used for local persistence.
  final AppDatabase _db;

  /// Domain validator for MOQ/conversion-factor configuration values.
  final MoqValidator _moqValidator;

  /// Domain validator for transport details required fields.
  final TransportValidator _transportValidator;

  /// RID generator for new entity identifiers.
  final RidGenerator _ridGenerator;

  WholesaleRepositoryImpl({
    SessionManager? sessionManager,
    AppDatabase? db,
    MoqValidator? moqValidator,
    TransportValidator? transportValidator,
    RidGenerator? ridGenerator,
  }) : _sessionManager = sessionManager ?? sl<SessionManager>(),
       _db = db ?? sl<AppDatabase>(),
       _moqValidator = moqValidator ?? const MoqValidator(),
       _transportValidator = transportValidator ?? const TransportValidator(),
       _ridGenerator = ridGenerator ?? DefaultRidGenerator();

  @override
  Future<T> withTenant<T>(Future<T> Function(String tenantId) op) async {
    final tenantId =
        _sessionManager.currentBusinessId ?? _sessionManager.userId;

    if (tenantId == null || tenantId.isEmpty) {
      throw UnresolvedTenantError();
    }

    return op(tenantId);
  }

  @override
  Future<void> saveMoq(String productId, int moqValue) {
    // Configuration-time validation: reject zero/negative/invalid MOQ (§14).
    final configResult = _moqValidator.validateConfig(
      moq: moqValue,
      conversionFactor: 1, // only validating MOQ here; factor is a dummy pass
    );
    if (configResult.isInvalid) {
      throw ArgumentError((configResult as ValidationFailure).reason);
    }

    return withTenant<void>((tenantId) async {
      // Update the product's MOQ column, scoped to this tenant.
      // Uses raw SQL to avoid dependency on not-yet-regenerated Drift
      // companions (build_runner must run after the column addition).
      await _db.customStatement(
        'UPDATE products SET moq = ? WHERE id = ? AND user_id = ?',
        [moqValue, productId, tenantId],
      );
    });
  }

  @override
  Future<void> saveUnitConversionFactor(String productId, int factor) {
    // Configuration-time validation: reject zero/negative/invalid factor (§14).
    final configResult = _moqValidator.validateConfig(
      moq: 1, // only validating factor here; moq is a dummy pass
      conversionFactor: factor,
    );
    if (configResult.isInvalid) {
      throw ArgumentError((configResult as ValidationFailure).reason);
    }

    return withTenant<void>((tenantId) async {
      // Update the product's unitConversionFactor column, scoped to tenant.
      // Uses raw SQL to avoid dependency on not-yet-regenerated Drift
      // companions (build_runner must run after the column addition).
      await _db.customStatement(
        'UPDATE products SET unit_conversion_factor = ? WHERE id = ? AND user_id = ?',
        [factor, productId, tenantId],
      );
    });
  }

  @override
  Future<TransportDetails> saveTransport(TransportDetails details) {
    // Validate required fields BEFORE any persistence (Requirement 8.6).
    final validationResult = _transportValidator.validate(
      vehicleNumber: details.vehicleNumber,
      transporterName: details.transporterName,
      lrNumber: details.lrNumber,
    );

    if (validationResult.isInvalid) {
      throw ArgumentError((validationResult as ValidationFailure).reason);
    }

    return withTenant<TransportDetails>((tenantId) async {
      // Generate RID: {tenantId}-{timestamp_ms}-{uuid_v4_short}
      final id = _ridGenerator.generate(tenantId);
      final now = DateTime.now();

      // Persist to the transport_details_table, scoped to this tenant.
      await _db.customStatement(
        'INSERT INTO transport_details_table '
        '(id, tenant_id, vehicle_number, lr_number, transporter_name, '
        'linked_challan_id, created_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?)',
        [
          id,
          tenantId,
          details.vehicleNumber.trim(),
          details.lrNumber.trim(),
          details.transporterName.trim(),
          details.linkedChallanId,
          now.millisecondsSinceEpoch,
        ],
      );

      // Return the persisted entity with assigned RID and tenant.
      return TransportDetails(
        id: id,
        tenantId: tenantId,
        vehicleNumber: details.vehicleNumber.trim(),
        lrNumber: details.lrNumber.trim(),
        transporterName: details.transporterName.trim(),
        linkedChallanId: details.linkedChallanId,
        createdAt: now,
      );
    });
  }

  @override
  Future<void> saveCreditLimit(String partyId, int limitPaise) {
    if (limitPaise < 0) {
      throw ArgumentError('Credit limit cannot be negative: $limitPaise');
    }

    return withTenant<void>((tenantId) async {
      // The existing creditLimit column is a RealColumn (float, rupees).
      // Convert paise → rupees for storage.
      final limitRupees = limitPaise / 100.0;

      await _db.customStatement(
        'UPDATE customers SET credit_limit = ? WHERE id = ? AND user_id = ?',
        [limitRupees, partyId, tenantId],
      );
    });
  }

  @override
  Future<int> nearCreditLimitCount() {
    return withTenant<int>((tenantId) async {
      // Query customers where outstanding (total_dues) >= 80% of creditLimit,
      // both > 0, scoped by tenant. The creditLimit is stored as rupees
      // (RealColumn), and total_dues is also rupees — comparison is valid
      // in the same unit without paise conversion.
      final results = await _db
          .customSelect(
            'SELECT COUNT(*) AS cnt FROM customers '
            'WHERE user_id = ? '
            'AND credit_limit > 0 '
            'AND total_dues >= (credit_limit * 0.8) '
            'AND is_active = 1',
            variables: [Variable<String>(tenantId)],
          )
          .get();

      if (results.isEmpty) return 0;
      return results.first.read<int>('cnt');
    });
  }

  // ==========================================================================
  // Phase 7 — Godown / Multi-Warehouse (Requirement 10)
  // ==========================================================================

  @override
  Future<Warehouse> saveWarehouse(Warehouse w) {
    if (w.name.trim().isEmpty) {
      throw ArgumentError('Warehouse name must not be empty');
    }

    return withTenant<Warehouse>((tenantId) async {
      // Generate RID: {tenantId}-{timestamp_ms}-{uuid_v4_short}
      final id = _ridGenerator.generate(tenantId);
      final now = DateTime.now();

      await _db.customStatement(
        'INSERT INTO warehouses_table (id, tenant_id, name, created_at) '
        'VALUES (?, ?, ?, ?)',
        [id, tenantId, w.name.trim(), now.millisecondsSinceEpoch],
      );

      return Warehouse(
        id: id,
        tenantId: tenantId,
        name: w.name.trim(),
        createdAt: now,
      );
    });
  }

  @override
  Future<List<Warehouse>> getWarehousesForTenant() {
    return withTenant<List<Warehouse>>((tenantId) async {
      final results = await _db
          .customSelect(
            'SELECT id, tenant_id, name, created_at FROM warehouses_table '
            'WHERE tenant_id = ? ORDER BY created_at ASC',
            variables: [Variable<String>(tenantId)],
          )
          .get();

      return results.map((row) {
        return Warehouse(
          id: row.read<String>('id'),
          tenantId: row.read<String>('tenant_id'),
          name: row.read<String>('name'),
          createdAt: DateTime.fromMillisecondsSinceEpoch(
            row.read<int>('created_at'),
          ),
        );
      }).toList();
    });
  }

  @override
  Future<void> recordStockMovement(
    String locationId,
    String productId,
    int quantityDelta,
  ) {
    return withTenant<void>((tenantId) async {
      // Verify the warehouse belongs to the active tenant (Requirement 10.4).
      final warehouseResults = await _db
          .customSelect(
            'SELECT tenant_id FROM warehouses_table '
            'WHERE id = ? AND tenant_id = ?',
            variables: [
              Variable<String>(locationId),
              Variable<String>(tenantId),
            ],
          )
          .get();

      if (warehouseResults.isEmpty) {
        throw ForeignTenantMovementError(
          locationId: locationId,
          activeTenantId: tenantId,
        );
      }

      // Upsert: INSERT OR REPLACE with the updated quantity.
      // First, read the current quantity (if any).
      final existing = await _db
          .customSelect(
            'SELECT quantity FROM stock_by_location_table '
            'WHERE tenant_id = ? AND product_id = ? AND location_id = ?',
            variables: [
              Variable<String>(tenantId),
              Variable<String>(productId),
              Variable<String>(locationId),
            ],
          )
          .get();

      final currentQty = existing.isNotEmpty
          ? existing.first.read<int>('quantity')
          : 0;
      final newQty = currentQty + quantityDelta;

      // Use INSERT OR REPLACE to upsert the stock record.
      await _db.customStatement(
        'INSERT OR REPLACE INTO stock_by_location_table '
        '(tenant_id, product_id, location_id, quantity) '
        'VALUES (?, ?, ?, ?)',
        [tenantId, productId, locationId, newQty],
      );
    });
  }

  // ==========================================================================
  // Phase 8 — Tiered/Slab Pricing & Party Rate Lists (Requirement 11)
  // ==========================================================================

  @override
  Future<RateList> saveRateList(RateList rateList) {
    if (rateList.productId.trim().isEmpty) {
      throw ArgumentError('Rate list must have a non-empty productId');
    }
    if (rateList.slabs.isEmpty) {
      throw ArgumentError('Rate list must have at least one pricing slab');
    }

    return withTenant<RateList>((tenantId) async {
      final id = rateList.id.isEmpty
          ? _ridGenerator.generate(tenantId)
          : rateList.id;
      final now = DateTime.now();

      // Serialize slabs as JSON TEXT.
      final slabsJson = jsonEncode(
        rateList.slabs.map((s) => s.toJson()).toList(),
      );

      // Upsert: INSERT OR REPLACE on the rate_lists_table.
      await _db.customStatement(
        'INSERT OR REPLACE INTO rate_lists_table '
        '(id, tenant_id, party_id, product_id, slabs_json, created_at) '
        'VALUES (?, ?, ?, ?, ?, ?)',
        [
          id,
          tenantId,
          rateList.partyId,
          rateList.productId.trim(),
          slabsJson,
          now.millisecondsSinceEpoch,
        ],
      );

      return RateList(
        id: id,
        tenantId: tenantId,
        partyId: rateList.partyId,
        productId: rateList.productId.trim(),
        slabs: rateList.slabs,
        createdAt: now,
      );
    });
  }

  @override
  Future<List<RateList>> getRateListsForProduct(
    String productId, {
    String? partyId,
  }) {
    return withTenant<List<RateList>>((tenantId) async {
      final String query;
      final List<dynamic> variables;

      if (partyId != null) {
        query =
            'SELECT id, tenant_id, party_id, product_id, slabs_json, created_at '
            'FROM rate_lists_table '
            'WHERE tenant_id = ? AND product_id = ? AND party_id = ? '
            'ORDER BY created_at ASC';
        variables = [
          Variable<String>(tenantId),
          Variable<String>(productId),
          Variable<String>(partyId),
        ];
      } else {
        query =
            'SELECT id, tenant_id, party_id, product_id, slabs_json, created_at '
            'FROM rate_lists_table '
            'WHERE tenant_id = ? AND product_id = ? '
            'ORDER BY created_at ASC';
        variables = [Variable<String>(tenantId), Variable<String>(productId)];
      }

      final results = await _db
          .customSelect(query, variables: variables.cast<Variable>())
          .get();

      return results.map((row) => _rowToRateList(row)).toList();
    });
  }

  @override
  Future<List<RateList>> getAllRateLists() {
    return withTenant<List<RateList>>((tenantId) async {
      final results = await _db
          .customSelect(
            'SELECT id, tenant_id, party_id, product_id, slabs_json, created_at '
            'FROM rate_lists_table '
            'WHERE tenant_id = ? '
            'ORDER BY created_at DESC',
            variables: [Variable<String>(tenantId)],
          )
          .get();

      return results.map((row) => _rowToRateList(row)).toList();
    });
  }

  /// Converts a Drift query row to a [RateList] domain object.
  RateList _rowToRateList(QueryRow row) {
    final slabsRaw = jsonDecode(row.read<String>('slabs_json')) as List;
    final slabs = slabsRaw
        .map((s) => PricingSlab.fromJson(s as Map<String, dynamic>))
        .toList();

    return RateList(
      id: row.read<String>('id'),
      tenantId: row.read<String>('tenant_id'),
      partyId: row.readNullable<String>('party_id'),
      productId: row.read<String>('product_id'),
      slabs: slabs,
      createdAt: DateTime.fromMillisecondsSinceEpoch(
        row.read<int>('created_at'),
      ),
    );
  }

  // ==========================================================================
  // Phase 9 — E-Way Bill Records (Requirement 12)
  // ==========================================================================

  @override
  Future<EWayRecord> saveEWay(EWayRecord record) {
    // Validate capture fields before persistence.
    const ewayRules = EWayRules();
    final capture = EWayCapture(
      transporterName: record.transporterName,
      approxDistanceKm: record.approxDistanceKm,
      vehicleNumber: record.vehicleNumber,
      partyGstin: record.partyGstin,
    );
    final validation = ewayRules.validateCapture(capture);
    if (validation.isInvalid) {
      throw ArgumentError((validation as ValidationFailure).reason);
    }

    return withTenant<EWayRecord>((tenantId) async {
      // Generate RID: {tenantId}-{timestamp_ms}-{uuid_v4_short}
      final id = _ridGenerator.generate(tenantId);
      final now = DateTime.now();

      // Per External_Dependency_Gate (GSP_Credentials-unavailable):
      // - ewayNumber is ALWAYS null
      // - status is ALWAYS 'blocked'
      // NEVER fabricate, mock, or simulate an e-Way number.
      const status = EWayStatus.blocked;
      const String? ewayNumber = null;

      await _db.customStatement(
        'INSERT INTO eway_records_table '
        '(id, tenant_id, consignment_paise, inter_state, transporter_name, '
        'approx_distance_km, vehicle_number, party_gstin, eway_number, '
        'status, created_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
        [
          id,
          tenantId,
          record.consignmentPaise,
          record.interState ? 1 : 0,
          record.transporterName.trim(),
          record.approxDistanceKm,
          record.vehicleNumber.trim(),
          record.partyGstin.trim(),
          ewayNumber,
          status.name, // 'blocked'
          now.millisecondsSinceEpoch,
        ],
      );

      return EWayRecord(
        id: id,
        tenantId: tenantId,
        consignmentPaise: record.consignmentPaise,
        interState: record.interState,
        transporterName: record.transporterName.trim(),
        approxDistanceKm: record.approxDistanceKm,
        vehicleNumber: record.vehicleNumber.trim(),
        partyGstin: record.partyGstin.trim(),
        ewayNumber: ewayNumber,
        status: status,
        createdAt: now,
      );
    });
  }
}
