import 'package:drift/drift.dart';
import '../../../../core/database/app_database.dart';

import '../../../../core/error/error_handler.dart';
import '../../../../core/session/owner_id_resolver.dart';
import '../../../../core/session/session_manager.dart';
import '../../../../core/sync/sync_manager.dart';
import '../../../../core/sync/sync_queue_state_machine.dart';
import '../../models/appointment_model.dart';
import '../exceptions/double_booking_exception.dart';
// Note: AppointmentEntity should be generated by Drift from 'Appointments' table

class AppointmentRepository {
  final AppDatabase _db;
  final SyncManager _syncManager;

  /// Optional session override for tests. In production this is null and the
  /// shared [resolveOwnerId] falls back to the registered [SessionManager]
  /// singleton (the same owner-id source `clinic_billing_service` uses).
  final SessionManager? _session;

  AppointmentRepository({
    required AppDatabase db,
    required SyncManager syncManager,
    SessionManager? session,
  }) : _db = db,
       _syncManager = syncManager,
       _session = session;

  // ==========================================================================
  // DOUBLE-BOOKING GUARD
  // ==========================================================================

  /// Checks whether [appointment]'s proposed slot overlaps any existing
  /// non-cancelled appointment for the same doctor.
  ///
  /// Overlap definition: two slots overlap when
  ///   proposedStart < existingEnd AND existingStart < proposedEnd
  ///
  /// Throws [DoubleBookingException] if an overlap is detected.
  /// This is intentionally extracted as a testable method.
  Future<void> guardAgainstDoubleBooking(AppointmentModel appointment) async {
    final proposedStart = appointment.scheduledTime;
    final proposedEnd = appointment.slotEndTime;

    // Query existing non-cancelled appointments for this doctor that could
    // overlap. We use a generous time window (same day ± 1 day) and then
    // do precise overlap checks in Dart to handle the slot-duration math
    // that SQLite can't easily compute (since slotDurationMinutes is nullable
    // and needs a default applied at the app layer).
    final dayStart = DateTime(
      proposedStart.year,
      proposedStart.month,
      proposedStart.day,
    ).subtract(const Duration(days: 1));
    final dayEnd = dayStart.add(const Duration(days: 3));

    final existingRows =
        await (_db.select(_db.appointments)..where(
              (t) =>
                  t.doctorId.equals(appointment.doctorId) &
                  t.scheduledTime.isBiggerOrEqualValue(dayStart) &
                  t.scheduledTime.isSmallerThanValue(dayEnd) &
                  t.status.isNotIn(['cancelled', 'CANCELLED']) &
                  t.id.isNotValue(appointment.id), // exclude self on updates
            ))
            .get();

    for (final existing in existingRows) {
      final existingStart = existing.scheduledTime;
      // Use app-layer default when slotDurationMinutes is NULL.
      final existingDuration =
          existing.slotDurationMinutes ?? AppointmentModel.defaultSlotDuration;
      final existingEnd = existingStart.add(
        Duration(minutes: existingDuration),
      );

      // Overlap check: proposedStart < existingEnd AND existingStart < proposedEnd
      if (proposedStart.isBefore(existingEnd) &&
          existingStart.isBefore(proposedEnd)) {
        throw DoubleBookingException(
          doctorId: appointment.doctorId,
          proposedAppointmentId: appointment.id,
          conflictingAppointmentId: existing.id,
          conflictingTime: existingStart,
        );
      }
    }
  }

  /// Create Appointment
  Future<void> createAppointment(AppointmentModel appointment) async {
    try {
      // Fail-safe tenant attribution: resolve the real owner id before the
      // sync enqueue. Missing owner id throws and blocks the write.
      final ownerId = resolveOwnerId(
        session: _session,
        operation: 'create appointment',
      );

      // Double-booking guard: reject if the proposed slot overlaps an existing
      // non-cancelled appointment for the same doctor.
      await guardAgainstDoubleBooking(appointment);

      await _db
          .into(_db.appointments)
          .insert(
            AppointmentsCompanion.insert(
              id: appointment.id,
              doctorId: appointment.doctorId,
              patientId: appointment.patientId,
              scheduledTime: appointment.scheduledTime,
              status: Value(appointment.status.name),
              purpose: Value(appointment.purpose),
              notes: Value(appointment.notes),
              slotDurationMinutes: Value(appointment.slotDurationMinutes),
              createdAt: appointment.createdAt,
              updatedAt: appointment.updatedAt,
            ),
          );

      await _syncManager.enqueue(
        SyncQueueItem.create(
          userId: ownerId,
          operationType: SyncOperationType.create,
          targetCollection: 'appointments',
          documentId: appointment.id,
          payload: appointment.toMap(),
          priority: 1,
        ),
      );
    } catch (e, stack) {
      // Re-throw DoubleBookingException directly — the caller handles it.
      if (e is DoubleBookingException) rethrow;
      ErrorHandler.handle(
        e,
        stackTrace: stack,
        userMessage: 'Failed to create appointment',
      );
      rethrow;
    }
  }

  /// Update Appointment
  Future<void> updateAppointment(AppointmentModel appointment) async {
    try {
      final ownerId = resolveOwnerId(
        session: _session,
        operation: 'update appointment',
      );
      await (_db.update(
        _db.appointments,
      )..where((t) => t.id.equals(appointment.id))).write(
        AppointmentsCompanion(
          scheduledTime: Value(appointment.scheduledTime),
          status: Value(appointment.status.name),
          purpose: Value(appointment.purpose),
          notes: Value(appointment.notes),
          slotDurationMinutes: Value(appointment.slotDurationMinutes),
          updatedAt: Value(DateTime.now()),
        ),
      );

      await _syncManager.enqueue(
        SyncQueueItem.create(
          userId: ownerId,
          operationType: SyncOperationType.update,
          targetCollection: 'appointments',
          documentId: appointment.id,
          payload: appointment.toMap(),
          priority: 1,
        ),
      );
    } catch (e, stack) {
      ErrorHandler.handle(
        e,
        stackTrace: stack,
        userMessage: 'Failed to update appointment',
      );
      rethrow;
    }
  }

  /// Get Appointments for Doctor (by Date Range)
  Future<List<AppointmentModel>> getAppointmentsForDoctor(
    String doctorId,
    DateTime start,
    DateTime end,
  ) async {
    final rows =
        await (_db.select(_db.appointments)
              ..where(
                (t) =>
                    t.doctorId.equals(doctorId) &
                    t.scheduledTime.isBiggerOrEqualValue(start) &
                    t.scheduledTime.isSmallerOrEqualValue(end),
              )
              ..orderBy([(t) => OrderingTerm.asc(t.scheduledTime)]))
            .get();
    return rows.map((row) => _mapToModel(row)).toList();
  }

  /// Watch Appointments for Doctor (Reactive)
  Stream<List<AppointmentModel>> watchAppointmentsForDoctor(
    String doctorId,
    DateTime date,
  ) {
    // Filter for the specific day
    final startOfDay = DateTime(date.year, date.month, date.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    return (_db.select(_db.appointments)
          ..where(
            (t) =>
                t.doctorId.equals(doctorId) &
                t.scheduledTime.isBiggerOrEqualValue(startOfDay) &
                t.scheduledTime.isSmallerThanValue(endOfDay),
          )
          ..orderBy([(t) => OrderingTerm.asc(t.scheduledTime)]))
        .watch()
        .map((rows) => rows.map((row) => _mapToModel(row)).toList());
  }

  /// Watch Appointments for Patient (Reactive)
  Stream<List<AppointmentModel>> watchAppointmentsForPatient(String patientId) {
    return (_db.select(_db.appointments)
          ..where((t) => t.patientId.equals(patientId))
          ..orderBy([(t) => OrderingTerm.asc(t.scheduledTime)]))
        .watch()
        .map((rows) => rows.map((row) => _mapToModel(row)).toList());
  }

  AppointmentModel _mapToModel(AppointmentEntity row) {
    return AppointmentModel(
      id: row.id,
      doctorId: row.doctorId,
      patientId: row.patientId,
      scheduledTime: row.scheduledTime,
      status: AppointmentStatus.values.firstWhere(
        (e) => e.name == row.status,
        orElse: () => AppointmentStatus.scheduled,
      ),
      purpose: row.purpose,
      notes: row.notes,
      slotDurationMinutes: row.slotDurationMinutes,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    );
  }
}
