/// Quality-gate reducers for performance and security gates.
///
/// Pure logic: reduces measurement/test-case evidence to a gate status
/// (green or notGreen) and generates defect descriptions for offending
/// metrics or categories. No I/O.
///
/// Requirements: 9.3, 9.4, 9.6, 10.1, 10.5
library;

/// Gate status: green means the gate passed; notGreen means it failed.
enum GateStatus { green, notGreen }

/// Whether a threshold comes from the default configuration or has been
/// tuned via external config.
enum ThresholdSource { defaultSource, tuned }

/// Performance thresholds — tunable via configuration (Req 9.2).
///
/// Defaults:
/// - Cold-start: 5000 ms
/// - Report generation: 10000 ms
/// - Synchronization: 60000 ms
/// - Min FPS: 30 (no single frame > 33 ms)
/// - Dataset records: 10000
class PerfThresholds {
  /// Maximum cold-start time in milliseconds.
  final int coldStartMs;

  /// Maximum report-generation time in milliseconds.
  final int reportGenMs;

  /// Maximum synchronization time in milliseconds.
  final int syncMs;

  /// Minimum sustained frames per second (no frame > 33 ms).
  final int minFps;

  /// Number of records in the test dataset.
  final int datasetRecords;

  /// Whether these thresholds are defaults or have been tuned.
  final ThresholdSource source;

  const PerfThresholds({
    this.coldStartMs = 5000,
    this.reportGenMs = 10000,
    this.syncMs = 60000,
    this.minFps = 30,
    this.datasetRecords = 10000,
    this.source = ThresholdSource.defaultSource,
  });
}

/// A single performance measurement for a metric.
///
/// [measured] is null when the measurement could not be completed (Req 9.6).
class PerfMeasurement {
  /// Name of the metric (e.g. 'coldStart', 'reportGen', 'sync', 'fps').
  final String metric;

  /// The measured value, or null if the measurement couldn't be completed.
  final num? measured;

  /// The threshold this measurement is compared against.
  final num threshold;

  /// Source of the threshold (default or tuned).
  final ThresholdSource source;

  /// Number of records in the test dataset used for this measurement.
  final int datasetRecords;

  const PerfMeasurement({
    required this.metric,
    required this.measured,
    required this.threshold,
    this.source = ThresholdSource.defaultSource,
    this.datasetRecords = 10000,
  });

  /// Whether this metric is within its threshold.
  ///
  /// For 'fps' (minFps), within means measured >= threshold.
  /// For all other metrics (time-based), within means measured <= threshold.
  /// Returns false if [measured] is null (not measured).
  bool get isWithinThreshold {
    final m = measured;
    if (m == null) return false;
    if (metric == 'fps') {
      return m >= threshold;
    }
    return m <= threshold;
  }
}

/// The five security testing categories (Req 10.1).
enum SecurityCategory {
  authBypass,
  roleEscalation,
  insecureStorage,
  apiAuthorization,
  licenseTamper,
}

/// Result of a single security test case.
class SecurityCaseResult {
  /// Which security category this case belongs to.
  final SecurityCategory category;

  /// Human-readable name of the test case.
  final String caseName;

  /// True means no vulnerability was found (the case passed).
  /// False means a vulnerability was detected.
  final bool passed;

  /// The affected endpoint or case identifier (optional).
  final String? endpoint;

  const SecurityCaseResult({
    required this.category,
    required this.caseName,
    required this.passed,
    this.endpoint,
  });
}

/// A defect description generated by the gate reducer.
///
/// Contains enough detail to create a full [Defect] record downstream.
class GateDefect {
  /// A short description of the offending item.
  final String description;

  /// The metric name or security category that triggered this defect.
  final String offendingItem;

  /// The measured value (as string), or 'not measured' if unavailable.
  final String measuredValue;

  /// The threshold or expected condition.
  final String threshold;

  const GateDefect({
    required this.description,
    required this.offendingItem,
    required this.measuredValue,
    required this.threshold,
  });
}

/// Pure reducer that decides gate status from evidence.
///
/// The reducer is deterministic and performs no I/O. It also exposes
/// defect-generation methods that return detailed descriptions of
/// offending metrics/categories with measurements retained.
class GateStatusReducer {
  const GateStatusReducer();

  // ─── Performance Gate ─────────────────────────────────────────────────

  /// Pure: green iff every measurement is non-null AND within its threshold.
  ///
  /// - If any measurement has [PerfMeasurement.measured] == null, the gate
  ///   fails (metric could not be measured — Req 9.6).
  /// - If any measurement's value exceeds its threshold, the gate fails
  ///   (Req 9.3).
  /// - Green only when all measurements are present and within bounds (Req 9.4).
  GateStatus reducePerformance(List<PerfMeasurement> measurements) {
    if (measurements.isEmpty) return GateStatus.notGreen;
    for (final m in measurements) {
      if (!m.isWithinThreshold) return GateStatus.notGreen;
    }
    return GateStatus.green;
  }

  /// Returns one [GateDefect] per offending performance metric.
  ///
  /// An offending metric is one where [PerfMeasurement.measured] is null
  /// (could not be completed) or where the measured value exceeds the threshold.
  /// All measurements are retained in the output regardless of pass/fail status.
  List<GateDefect> performanceDefects(List<PerfMeasurement> measurements) {
    final defects = <GateDefect>[];
    for (final m in measurements) {
      if (m.isWithinThreshold) continue;

      final measuredStr = m.measured == null
          ? 'not measured'
          : m.measured.toString();

      final thresholdStr = m.metric == 'fps'
          ? '>= ${m.threshold}'
          : '<= ${m.threshold}';

      defects.add(
        GateDefect(
          description: m.measured == null
              ? 'Performance metric "${m.metric}" could not be measured '
                    '(dataset: ${m.datasetRecords} records, '
                    'threshold source: ${m.source.name})'
              : 'Performance metric "${m.metric}" exceeded threshold: '
                    'measured $measuredStr vs threshold $thresholdStr '
                    '(dataset: ${m.datasetRecords} records, '
                    'threshold source: ${m.source.name})',
          offendingItem: m.metric,
          measuredValue: measuredStr,
          threshold: thresholdStr,
        ),
      );
    }
    return defects;
  }

  // ─── Security Gate ────────────────────────────────────────────────────

  /// Pure: green iff zero failing security cases across all five categories.
  ///
  /// A failing case is one where [SecurityCaseResult.passed] is false (a
  /// vulnerability was detected). The gate is green only when every case
  /// in every category passed (Req 10.1, 10.5).
  GateStatus reduceSecurity(List<SecurityCaseResult> cases) {
    for (final c in cases) {
      if (!c.passed) return GateStatus.notGreen;
    }
    return GateStatus.green;
  }

  /// Returns one [GateDefect] per security category that has at least one
  /// failing case.
  ///
  /// Exactly one defect per offending category (not per individual failing
  /// case), naming the affected endpoints/cases. This matches Req 10.1:
  /// "record one Defect per category in which any test case fails".
  List<GateDefect> securityDefects(List<SecurityCaseResult> cases) {
    // Group failing cases by category.
    final failingByCategory = <SecurityCategory, List<SecurityCaseResult>>{};
    for (final c in cases) {
      if (!c.passed) {
        failingByCategory.putIfAbsent(c.category, () => []).add(c);
      }
    }

    final defects = <GateDefect>[];
    for (final entry in failingByCategory.entries) {
      final category = entry.key;
      final failing = entry.value;

      // Collect affected endpoints/case names for the defect description.
      final affectedItems = failing
          .map((f) => f.endpoint ?? f.caseName)
          .toList();

      defects.add(
        GateDefect(
          description:
              'Security category "${category.name}" has ${failing.length} '
              'failing case(s): ${affectedItems.join(', ')}',
          offendingItem: category.name,
          measuredValue: '${failing.length} failing case(s)',
          threshold: '0 failing cases',
        ),
      );
    }
    return defects;
  }
}
