/**
 * Mobile Shop Remediation Ledger Data
 *
 * Version-controlled AF-01–AF-53 remediation entries.
 * Each entry records current evidence, root cause, dependencies,
 * requirement/design/task links, planned changes, status, changed files,
 * and completion evidence.
 */

import { RemediationLedger, RemediationEntry } from './ledger.types';

const findings: RemediationEntry[] = [
  {
    id: 'AF-01',
    title: 'Generic retail sidebar — no mobile-specific entries',
    currentEvidence: 'mobileShop uses _getRetailSections() which renders ~60 generic items with zero mobile tools (IMEI, repair, exchange, warranty, second-hand)',
    rootCause: '_getSectionsForBusiness groups mobileShop with electronics/computerShop into generic retail sidebar',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '2.1' }, { requirementId: '2.2' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.1' }],
    plannedChanges: 'Add dedicated mobileShop sidebar section with service, exchange, IMEI, warranty, second-hand entries gated by capability',
    changedFiles: [],
    auditSection: '§1, §6, §18',
  },
  {
    id: 'AF-02',
    title: 'Missing mobile tools in sidebar despite granted capabilities',
    currentEvidence: 'useIMEI, useWarranty, useBuyback, useExchange, useJobSheets, useRepairStatus granted but no corresponding sidebar items exist in _getRetailSections',
    rootCause: 'Capability-vs-sidebar mismatch: capabilities granted without UI surface',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-01'],
    requirementLinks: [{ requirementId: '2.1' }, { requirementId: '2.2' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.1' }],
    plannedChanges: 'Expose dedicated entries matching each granted capability in the mobile sidebar',
    changedFiles: [],
    auditSection: '§1, §6',
  },
  {
    id: 'AF-03',
    title: 'Configuration/capability mismatch — modules declared but not surfaced',
    currentEvidence: 'Config declares modules repairs/second_hand but sidebar renders neither; _getServiceSections exists but only wired to BusinessType.service',
    rootCause: 'Module config is metadata only, not used for sidebar generation',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-01'],
    requirementLinks: [{ requirementId: '2.1' }, { requirementId: '2.2' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.1' }],
    plannedChanges: 'Wire mobileShop sidebar to include service/repair and second-hand sections matching declared modules',
    changedFiles: [],
    auditSection: '§1, §13, §18',
  },
  {
    id: 'AF-04',
    title: 'Obsolete parallel mobile module/router architecture',
    currentEvidence: 'MobileShopModule exposes GoRouter routes and navItems but app uses MaterialApp.routes; entire module is orphaned and unreachable',
    rootCause: 'Legacy module system built for GoRouter never mounted in the live MaterialApp.routes composition',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '1.4' }, { requirementId: '2.8' }],
    designLinks: [{ componentId: '1', componentName: 'Remediation Ledger and Traceability Gate' }],
    taskLinks: [{ taskId: '13.3' }],
    plannedChanges: 'Keep MaterialApp.router/appRouterProvider as sole composition; remove orphaned module routes after reachability evidence',
    changedFiles: [],
    auditSection: '§1, §6',
  },
  {
    id: 'AF-05',
    title: 'Partial billing — no unit-level IMEI tracking in invoicing',
    currentEvidence: 'Bill UI captures serialNo but does not enforce it as required; no per-IMEI unit tracking surfaced in inventory',
    rootCause: 'Bill field uses hasField (visibility) not isRequired; generic inventory has no unit concept',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-19'],
    requirementLinks: [{ requirementId: '3.1' }, { requirementId: '4.1' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '12.2' }],
    plannedChanges: 'Enforce IMEI as required field in mobileShop bills; add per-unit IMEI tracking to inventory',
    changedFiles: [],
    auditSection: '§2, §3',
  },
  {
    id: 'AF-06',
    title: 'Non-unit inventory — no per-IMEI stock segregation',
    currentEvidence: 'stock_summary/item_stock/low_stock are generic screens; no new-vs-used segregation or per-IMEI unit view',
    rootCause: 'Inventory model is quantity-based, not unit-based for device verticals',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '4.1' }, { requirementId: '4.9' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '14.1' }],
    plannedChanges: 'Implement IMEI_Unit model with lifecycle states; add inventory views distinguishing new/used/demo/reserved/sold/returned/damaged/retired',
    changedFiles: [],
    auditSection: '§2, §3',
  },
  {
    id: 'AF-07',
    title: 'Dead scan/POS action — IMEI Lookup quick action is no-op',
    currentEvidence: 'Dashboard "IMEI Lookup" quick action has onTap: () {} — visible, looks functional, does nothing',
    rootCause: 'Quick action placeholder implemented without wiring to serial history or scan functionality',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-12'],
    requirementLinks: [{ requirementId: '2.4' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.2' }],
    plannedChanges: 'Wire IMEI Lookup to tenant-scoped IMEI/serial history screen',
    changedFiles: [],
    auditSection: '§2, §3, §5',
  },
  {
    id: 'AF-08',
    title: 'Missing credit/EMI behavior',
    currentEvidence: 'Module navItem mobile_emi is a LegacyRouteRedirect to /payment-history (unmounted); useCreditManagement not granted; no EMI engine',
    rootCause: 'EMI/finance was stubbed in orphaned module but never implemented in live app',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-04'],
    requirementLinks: [{ requirementId: '10.1' }, { requirementId: '10.2' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Add provider-neutral finance/EMI APIs with feature-policy gating and domain persistence',
    changedFiles: [],
    auditSection: '§2, §3',
  },
  {
    id: 'AF-09',
    title: 'No IMEI-specific reservation/order flow',
    currentEvidence: 'booking_orders/dispatch_notes are generic retail; no mobile-specific reservation binding a specific IMEI unit',
    rootCause: 'Generic order system is quantity-based with no unit reservation concept',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-06'],
    requirementLinks: [{ requirementId: '4.6' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '7.1' }],
    plannedChanges: 'Implement IMEI-bound reservation claims through conditional writes that reject conflicting sale/reservation',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-10',
    title: 'OCR contradiction — ocrFocus defined but useScanOCR denied',
    currentEvidence: '_getOcrFocus(mobileShop) = "Name, Model, Serial/IMEI" but useScanOCR is not in mobileShop capability set',
    rootCause: 'ocrFocus metadata added without granting the required capability; electronics has it, mobileShop does not',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '10.8' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Add provider-neutral OCR port with feature-policy gate; grant capability or remove misleading focus metadata',
    changedFiles: [],
    auditSection: '§2, §13',
  },
  {
    id: 'AF-11',
    title: 'Missing mobile reports — no IMEI/brand/repair/exchange-specific reports',
    currentEvidence: 'analytics_hub, turnover_analysis, product_performance are generic retail reports; no IMEI-wise, brand-wise, repair-revenue, or exchange-margin reports',
    rootCause: 'Report screens are shared retail; no mobile-domain report implementation exists',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '9.7' }, { requirementId: '9.8' }, { requirementId: '9.9' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.4' }, { taskId: '15.2' }],
    plannedChanges: 'Implement tenant-bound reports for IMEI history, brand/model sales, unit margin, repair revenue, exchange margin, warranty, used-stock aging',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-12',
    title: 'Weak RBAC/audit semantics — no permission gating on sidebar items',
    currentEvidence: 'Only batch_tracking has a capability gate in _getRetailSections; no item carries a permission field; audit_trail just shows AllTransactionsScreen',
    rootCause: 'Sidebar items defined without permission metadata; content_host renders without role guard check',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '8.1' }, { requirementId: '8.2' }, { requirementId: '8.5' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '3.2' }, { taskId: '3.3' }],
    plannedChanges: 'Attach dedicated view/manage permissions to financial/compliance/admin items; enforce on content_host path',
    changedFiles: [],
    auditSection: '§2, §11',
  },
  {
    id: 'AF-13',
    title: 'Tenant identity inconsistency — divergent auth sources in service screens',
    currentEvidence: 'ServiceJobListScreen uses AuthService().currentUser?.uid; ExchangeListScreen uses FirebaseAuth.instance.currentUser?.uid',
    rootCause: 'Sibling screens in the same module use different identity resolution paths without a centralized TenantContext',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '5.8' }, { requirementId: '5.9' }],
    designLinks: [{ componentId: '2', componentName: 'Tenant Context and Policy' }],
    taskLinks: [{ taskId: '3.3' }],
    plannedChanges: 'Centralize tenant/identity resolution through one authoritative TenantContextResolver',
    changedFiles: [],
    auditSection: '§8, §11',
  },
  {
    id: 'AF-14',
    title: 'Unverified backup encryption',
    currentEvidence: 'backup sidebar item resolves to BackupScreen; encryption implementation unverified in audit',
    rootCause: 'Backup mechanism exists but encryption evidence not confirmed',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '6.39' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '8.5' }],
    plannedChanges: 'Verify or implement approved encrypted backup with separate operational identity and restore-drill automation',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-15',
    title: 'Generic catalogue — no mobile model attributes',
    currentEvidence: 'catalogue → CatalogueScreen is generic; no mobile-model specifics (brand, model, storage, color, condition)',
    rootCause: 'Catalogue is shared across all business types without domain-specific attribute extension',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '9.10' }, { requirementId: '9.11' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '15.3' }],
    plannedChanges: 'Add mobile model attributes and handset/accessory relationships without changing other catalogues',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-16',
    title: 'Missing e-Way bill support',
    currentEvidence: 'No e-Way screen found; only GSTR-1/HSN present',
    rootCause: 'e-Way bill implementation not built for any business type',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '10.11' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Integrate existing e-Way architecture with mobile shop compliance port',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-17',
    title: 'Missing loyalty/bundle engine',
    currentEvidence: 'useLoyaltyPoints not granted; no combo/accessory-bundle mechanism',
    rootCause: 'Loyalty and bundle features not implemented for mobile vertical',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '10.10' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Add bundle persistence with separate stock/tax/accounting lines and handset-accessory relationships',
    changedFiles: [],
    auditSection: '§2',
  },
  {
    id: 'AF-18',
    title: 'Unverified offline sync for mobile domain data',
    currentEvidence: 'MobileShopSyncHandler/MobileShopWsHandler registered through unmounted module system; live sync effect unverified/likely inactive',
    rootCause: 'Sync handlers exist but are registered via the orphaned GoRouter module system not the live app',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-04'],
    requirementLinks: [{ requirementId: '7.1' }, { requirementId: '7.4' }],
    designLinks: [{ componentId: '6', componentName: 'Local Drift Store and Sync Coordinator' }],
    taskLinks: [{ taskId: '11.2' }, { taskId: '11.3' }],
    plannedChanges: 'Implement durable offline sync through MobileSyncCoordinator bound to live TenantContext',
    changedFiles: [],
    auditSection: '§2, §12',
  },
  {
    id: 'AF-19',
    title: 'Unwired IMEI validation — service never injected',
    currentEvidence: 'service_locator.dart registers BillsRepository without imeiValidationService; field is nullable so guarded blocks are skipped at runtime',
    rootCause: 'DI registration omits imeiValidationService parameter; constructor field is nullable allowing silent skip',
    severity: 'critical',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '2.5' }, { requirementId: '2.6' }, { requirementId: '3.12' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '12.1' }, { taskId: '5.1' }],
    plannedChanges: 'Inject authoritative validator/orchestrator into BillsRepository; make dependency required for mobileShop',
    changedFiles: [],
    auditSection: '§3, §7, §14',
  },
  {
    id: 'AF-20',
    title: 'Non-required IMEI UI entry — empty IMEI can pass',
    currentEvidence: 'manual_item_entry_sheet.dart captures serialNo with no non-empty guard; uses hasField not isRequired',
    rootCause: 'UI field visibility and requirement are conflated; required-field logic not enforced at form level',
    severity: 'critical',
    status: 'open',
    dependencies: ['AF-19'],
    requirementLinks: [{ requirementId: '2.5' }, { requirementId: '3.1' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '12.2' }],
    plannedChanges: 'Enforce IMEI as required field using config.isRequired; block save on empty/invalid IMEI for mobileShop',
    changedFiles: [],
    auditSection: '§3, §4, §14',
  },
  {
    id: 'AF-21',
    title: 'Unreachable duplicate-sale prevention',
    currentEvidence: 'IMEISerialRepository.getByNumber + status checks exist but imeiValidationService is null so duplicate prevention never runs',
    rootCause: 'Service containing duplicate check logic is not injected (AF-19)',
    severity: 'critical',
    status: 'open',
    dependencies: ['AF-19'],
    requirementLinks: [{ requirementId: '3.9' }, { requirementId: '3.12' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '12.1' }, { taskId: '6.1' }],
    plannedChanges: 'Wire validation service and extend with authoritative DynamoDB uniqueness claims for concurrent protection',
    changedFiles: [],
    auditSection: '§3, §7, §14',
  },
  {
    id: 'AF-22',
    title: 'Missing used-stock/second-hand intake workflow',
    currentEvidence: 'Config declares module second_hand; useBuyback granted; no second-hand sidebar entry or intake screen found',
    rootCause: 'Module declared in config metadata but UI/backend not implemented',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-06'],
    requirementLinks: [{ requirementId: '4.2' }, { requirementId: '4.3' }, { requirementId: '4.4' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.1' }, { taskId: '14.1' }],
    plannedChanges: 'Implement second-hand intake with IMEI validation, seller identity, ownership evidence, inspection, valuation, and exchange linkage',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-23',
    title: 'Exchange/repair discoverability — only reachable via dashboard quick actions',
    currentEvidence: 'ExchangeListScreen and ServiceJobListScreen reachable only via dashboard quick actions, not sidebar; poor discoverability',
    rootCause: 'Screens exist but sidebar lacks entries (AF-01); content_host renders without equivalent route guards',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-01'],
    requirementLinks: [{ requirementId: '2.1' }, { requirementId: '2.3' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.1' }, { taskId: '13.2' }],
    plannedChanges: 'Add sidebar entries for service/exchange; enforce same permission policy on content_host path',
    changedFiles: [],
    auditSection: '§6',
  },
  {
    id: 'AF-24',
    title: 'Blocked warranty UI for mobileShop',
    currentEvidence: 'WarrantyScreen at /computer-shop/warranty has BusinessGuard(allowedTypes:[computerShop]) — mobileShop denied despite holding useWarranty',
    rootCause: 'Warranty screen guard explicitly restricts to computerShop only; mobileShop not added to allowed types',
    severity: 'critical',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '5.5' }, { requirementId: '5.8' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.2' }, { taskId: '14.2' }],
    plannedChanges: 'Widen device screens to approved verticals or create shared warranty screen accessible by mobileShop',
    changedFiles: [],
    auditSection: '§3, §4, §6, §13',
  },
  {
    id: 'AF-25',
    title: 'Blocked IMEI/serial history for mobileShop',
    currentEvidence: 'SerialHistoryScreen at /computer-shop/serial-history has BusinessGuard([computerShop]) — mobileShop denied despite useIMEI',
    rootCause: 'Guard explicitly restricts to computerShop; same fix pattern as AF-24',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '2.4' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.2' }],
    plannedChanges: 'Widen serial history screen guard to include mobileShop or create shared route',
    changedFiles: [],
    auditSection: '§3, §4, §6',
  },
  {
    id: 'AF-26',
    title: 'Blocked job card detail for mobileShop',
    currentEvidence: 'JobCardDetailScreen at /computer-shop/job-card/... has BusinessGuard([computerShop]) — mobileShop denied',
    rootCause: 'Guard restricts to computerShop only; mobileShop not included despite holding useJobSheets',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '5.8' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.2' }],
    plannedChanges: 'Include mobileShop in job card guards or route through shared device-service path',
    changedFiles: [],
    auditSection: '§6',
  },
  {
    id: 'AF-27',
    title: 'Missing EMI/finance plan support',
    currentEvidence: 'No EMI plan/financier engine; /mobile/emi is a LegacyRouteRedirect stub in orphaned module',
    rootCause: 'Feature was stubbed but never implemented',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-08'],
    requirementLinks: [{ requirementId: '10.1' }, { requirementId: '10.2' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }, { taskId: '14.3' }],
    plannedChanges: 'Implement finance plan domain persistence with provider-neutral APIs and feature-policy gating',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-28',
    title: 'Generic accessories — no attach-to-handset flow',
    currentEvidence: 'Accessories are plain inventory items; no accessory category or attach-to-handset flow',
    rootCause: 'No domain model for handset-accessory relationship in billing or inventory',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '4.8' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '15.3' }],
    plannedChanges: 'Add separate stock/tax lines for accessories with handset-accessory relationship for bundle reporting',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-29',
    title: 'Missing SIM/recharge functionality',
    currentEvidence: 'No recharge or SIM-activation screen located via grep',
    rootCause: 'Feature not implemented for any vertical',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '10.9' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Add provider-neutral SIM/recharge port with feature-policy gating',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-30',
    title: 'Missing price protection/MRP markdown logic',
    currentEvidence: 'Flat defaultGstRate 18.0; price label "MRP"; no price-protection or markdown logic',
    rootCause: 'No price-protection domain concept implemented',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '10.12' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '7.3' }],
    plannedChanges: 'Add price-protection with approval, margin impact, and audit trail',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-31',
    title: 'IMEI-aware returns missing — useSalesReturn not granted',
    currentEvidence: 'useSalesReturn not granted to mobileShop; generic return_inwards is not IMEI-aware',
    rootCause: 'Return flow has no IMEI/device lifecycle concept; capability not granted',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-06'],
    requirementLinks: [{ requirementId: '3.11' }, { requirementId: '4.7' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '7.1' }, { taskId: '14.1' }],
    plannedChanges: 'Implement IMEI-aware return with lifecycle transition, eligibility check, and immutable audit event',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-32',
    title: 'Missing demo-unit state in IMEI lifecycle',
    currentEvidence: 'IMEISerialStatus enum has inStock/sold/inService/returned/damaged but no demo state',
    rootCause: 'Demo use case not modeled in the existing IMEI status enum',
    severity: 'low',
    status: 'open',
    dependencies: ['AF-06'],
    requirementLinks: [{ requirementId: '4.5' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '5.2' }],
    plannedChanges: 'Add demo state to lifecycle; exclude demo units from saleable quantity',
    changedFiles: [],
    auditSection: '§3',
  },
  {
    id: 'AF-33',
    title: 'Hardcoded dashboard KPI counts — fake data shown as live',
    currentEvidence: 'business_alerts_widget.dart mobileShop branch emits literal "5", "8", "3" for warranty/repairs/exchange counts; ignores real providers',
    rootCause: 'Placeholder literals used instead of wiring to existing ServiceJobService.getJobCounts/ExchangeService.getExchangeStats',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '2.7' }, { requirementId: '9.1' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '15.1' }],
    plannedChanges: 'Replace hardcoded values with confirmation-aware live KPI providers; show loading/current/empty/stale/error states',
    changedFiles: [],
    auditSection: '§5, §8, §15',
  },
  {
    id: 'AF-34',
    title: 'Guard bypass — content_host renders without route permission check',
    currentEvidence: 'Repair/exchange screens rendered via content_host getScreenForItem without VendorRoleGuard that wraps equivalent named routes',
    rootCause: 'content_host dispatches screens by id without checking the permission that named routes enforce',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-12'],
    requirementLinks: [{ requirementId: '5.8' }, { requirementId: '8.3' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '3.3' }, { taskId: '13.2' }],
    plannedChanges: 'Apply equivalent business/capability/permission policy on content_host dispatch path',
    changedFiles: [],
    auditSection: '§11',
  },
  {
    id: 'AF-35',
    title: 'Dead business-type string branch in billing_service',
    currentEvidence: 'billing_service.dart gates on "mobile_shop" but enum name is "mobileShop" (camelCase) — never matches; body is a comment',
    rootCause: 'String literal uses wrong casing for Dart enum.name comparison',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '6.18' }],
    designLinks: [{ componentId: '2', componentName: 'Tenant Context and Policy' }],
    taskLinks: [{ taskId: '12.1' }],
    plannedChanges: 'Remove dead branch; route mobile sale through consistency orchestrator using canonical normalized value',
    changedFiles: [],
    auditSection: '§7, §17',
  },
  {
    id: 'AF-36',
    title: 'Absent backend reconciliation for mobile domain',
    currentEvidence: 'Service/exchange/warranty repositories operate over Drift directly; no server reconciliation for IMEI/sale state confirmed',
    rootCause: 'Sync handlers in orphaned module; no authoritative backend confirmation path for mobile domain mutations',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-18', 'AF-04'],
    requirementLinks: [{ requirementId: '3.4' }, { requirementId: '3.6' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '6.2' }, { taskId: '8.1' }],
    plannedChanges: 'Implement durable reconciliation with DynamoDB transactions, accepted-pending state, and conditional recovery',
    changedFiles: [],
    auditSection: '§7, §12',
  },
  {
    id: 'AF-37',
    title: 'Divergent identity sources across service screens',
    currentEvidence: 'ServiceJobListScreen uses AuthService().currentUser; ExchangeListScreen uses FirebaseAuth.instance.currentUser',
    rootCause: 'No single TenantContextResolver; screens independently access auth providers',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-13'],
    requirementLinks: [{ requirementId: '5.8' }, { requirementId: '5.9' }],
    designLinks: [{ componentId: '2', componentName: 'Tenant Context and Policy' }],
    taskLinks: [{ taskId: '3.3' }],
    plannedChanges: 'Unify through TenantContextResolver; render session-error state when context cannot be resolved',
    changedFiles: [],
    auditSection: '§8',
  },
  {
    id: 'AF-38',
    title: 'Responsive/theming inconsistency between service screens',
    currentEvidence: 'ServiceJobListScreen uses light AppBar with hardcoded Colors.grey; ExchangeListScreen uses dark-gradient custom header with hex colors',
    rootCause: 'Screens built independently without shared design tokens',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '11.1' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '16.1' }],
    plannedChanges: 'Apply shared theme tokens, responsive layouts, and consistent styling across all mobile service screens',
    changedFiles: [],
    auditSection: '§9',
  },
  {
    id: 'AF-39',
    title: 'Inefficient filtering — O(n) per keystroke without debounce',
    currentEvidence: 'ServiceJobListScreen._buildJobList applies .where() over full list on every onChanged keystroke with no debounce',
    rootCause: 'Search uses setState with inline filter on full collection; no debounce or bounded query',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '11.9' }, { requirementId: '11.10' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '16.2' }],
    plannedChanges: 'Move to debounced controller with bounded repository query and latest-query-wins semantics',
    changedFiles: [],
    auditSection: '§10',
  },
  {
    id: 'AF-40',
    title: 'Unsuitable permissions for repair workflows',
    currentEvidence: '/job/* and /service_jobs /exchanges require Permissions.manageStaff — a staff-management permission gating repair/exchange operations',
    rootCause: 'Wrong permission type assigned; should be operations/service permission',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-12'],
    requirementLinks: [{ requirementId: '8.1' }, { requirementId: '8.2' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '3.2' }],
    plannedChanges: 'Define dedicated mobile service/exchange permissions; migrate from manageStaff through compatibility matrix',
    changedFiles: [],
    auditSection: '§11',
  },
  {
    id: 'AF-41',
    title: 'Missing data-layer capability enforcement for IMEI',
    currentEvidence: 'useIMEI/useWarranty granted but IMEI enforcement service is unwired so hard isolation intent is not exercised on billing path',
    rootCause: 'Capability exists in metadata but data-layer enforcement depends on un-injected service (AF-19)',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-19'],
    requirementLinks: [{ requirementId: '2.6' }, { requirementId: '3.12' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '12.1' }],
    plannedChanges: 'Inject required IMEI validation into billing; fail closed when dependency absent for mobileShop',
    changedFiles: [],
    auditSection: '§11',
  },
  {
    id: 'AF-42',
    title: 'Weak IMEI format checks — no Luhn validation',
    currentEvidence: '_guessIMEIType treats any 15-digit numeric as IMEI; no Luhn checksum validation',
    rootCause: 'Type guesser uses only length heuristic without checksum verification',
    severity: 'medium',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '3.1' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '5.1' }],
    plannedChanges: 'Implement normalized IMEI validation with separator removal, 15 ASCII digits, and Luhn checksum in shared path',
    changedFiles: [],
    auditSection: '§13, §14',
  },
  {
    id: 'AF-43',
    title: 'Warranty date/range errors — month-end edge case',
    currentEvidence: 'markIMEIsAsSold computes warrantyEndDate with DateTime(year, month+N, day); day-of-month on 31st + N months rolls into next month',
    rootCause: 'Dart DateTime normalization on month overflow does not clamp day to target month end',
    severity: 'low',
    status: 'open',
    dependencies: ['AF-19'],
    requirementLinks: [{ requirementId: '5.7' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '5.3' }],
    plannedChanges: 'Use last valid day of target month for warranty calculation; validate configured ranges',
    changedFiles: [],
    auditSection: '§14',
  },
  {
    id: 'AF-44',
    title: 'Warranty months input — no range/negative guard',
    currentEvidence: 'int.tryParse(_warrantyController.text) with no range or negative guard',
    rootCause: 'Input parsing does not validate against documented configuration bounds',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '5.6' }],
    designLinks: [{ componentId: '4', componentName: 'Validation and Lifecycle Policies' }],
    taskLinks: [{ taskId: '5.3' }],
    plannedChanges: 'Validate warranty months against Documented_Configuration range; return field error for out-of-range',
    changedFiles: [],
    auditSection: '§14',
  },
  {
    id: 'AF-45',
    title: 'Accessibility gaps — status chips lack Semantics/tooltips',
    currentEvidence: 'Service/exchange cards use color+icon for status; custom tap targets (GestureDetector) lack Semantics; dead IMEI Lookup provides no disabled state',
    rootCause: 'Custom widgets built without semantic annotations for assistive technology',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '11.5' }, { requirementId: '11.6' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '16.1' }],
    plannedChanges: 'Add semantic labels, roles, states, 48x48 targets, visible focus, and non-color status indicators',
    changedFiles: [],
    auditSection: '§16',
  },
  {
    id: 'AF-46',
    title: 'Null-session spinner — no error state on missing userId',
    currentEvidence: 'ExchangeListScreen: if FirebaseAuth.instance.currentUser?.uid is null, _userId stays null and list shows perpetual spinner',
    rootCause: 'No session-error or signed-out fallback state when identity cannot be resolved',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-13'],
    requirementLinks: [{ requirementId: '5.9' }],
    designLinks: [{ componentId: '2', componentName: 'Tenant Context and Policy' }],
    taskLinks: [{ taskId: '13.4' }],
    plannedChanges: 'Render actionable signed-out/session-error state without domain access when TenantContext cannot be resolved',
    changedFiles: [],
    auditSection: '§17',
  },
  {
    id: 'AF-47',
    title: 'Dead status-card action — empty onTap in service job list',
    currentEvidence: 'Status card onTap in ServiceJobListScreen is empty closure with comment "// Filter by this status"',
    rootCause: 'Filter action placeholder never implemented',
    severity: 'low',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '5.10' }, { requirementId: '5.11' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.4' }, { taskId: '15.1' }],
    plannedChanges: 'Make interactive cards apply represented tenant-scoped filter; non-interactive cards expose semantic non-interactive state',
    changedFiles: [],
    auditSection: '§5, §17',
  },
  {
    id: 'AF-48',
    title: 'Non-mobile placeholder/remap surfaces in sidebar',
    currentEvidence: 'Multiple sidebar items resolve to same generic screens (AllTransactionsScreen, PnlScreen, CashflowScreen); none are mobile-aware',
    rootCause: 'Sidebar reuses generic screens that have no mobile domain concept',
    severity: 'medium',
    status: 'open',
    dependencies: ['AF-01'],
    requirementLinks: [{ requirementId: '2.1' }, { requirementId: '2.2' }],
    designLinks: [{ componentId: '3', componentName: 'Mobile Permissions and Route Catalog' }],
    taskLinks: [{ taskId: '13.1' }],
    plannedChanges: 'Exclude generic entries whose required capability is absent; route available labels only to matching functionality',
    changedFiles: [],
    auditSection: '§6, §18',
  },
  {
    id: 'AF-49',
    title: 'Non-atomic invoice/IMEI completion — silent data loss',
    currentEvidence: 'Sales of mobiles never record IMEIs because service is un-injected; duplicate IMEIs can be billed; no warranty linkage created',
    rootCause: 'No atomic completion path for invoice+IMEI state; depends on un-injected service (AF-19)',
    severity: 'critical',
    status: 'open',
    dependencies: ['AF-19', 'AF-21'],
    requirementLinks: [{ requirementId: '3.3' }, { requirementId: '3.4' }],
    designLinks: [{ componentId: '5', componentName: 'Mobile Sale Consistency Orchestrator' }],
    taskLinks: [{ taskId: '6.1' }, { taskId: '6.2' }],
    plannedChanges: 'Implement atomic DynamoDB transaction for invoice+IMEI+claims+idempotency+audit; use reconciliation for oversized operations',
    changedFiles: [],
    auditSection: '§7, §17',
  },
  {
    id: 'AF-50',
    title: 'Fragmented backend ownership — multiple backend roots',
    currentEvidence: 'Service/exchange repos operate over Drift; sync handlers in orphaned module; no single authoritative backend path for mobile domain',
    rootCause: 'Mobile domain data written locally without authoritative backend confirmation path',
    severity: 'high',
    status: 'open',
    dependencies: ['AF-04', 'AF-36'],
    requirementLinks: [{ requirementId: '6.1' }, { requirementId: '6.2' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }],
    taskLinks: [{ taskId: '8.4' }],
    plannedChanges: 'Consolidate all mobile domain persistence under Dukan_x/my-backend; remove non-authoritative paths after migration evidence',
    changedFiles: [],
    auditSection: '§7',
  },
  {
    id: 'AF-51',
    title: 'Absent cloud domain contracts for mobile shop',
    currentEvidence: 'No DynamoDB table, access patterns, tenant-bound keys, or API contracts defined for mobile domain entities',
    rootCause: 'Backend infrastructure for mobile domain not yet provisioned',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '6.1' }, { requirementId: '6.3' }, { requirementId: '6.6' }],
    designLinks: [{ componentId: '8', componentName: 'Canonical Backend Module' }, { componentId: '10', componentName: 'Access-Pattern Catalog' }],
    taskLinks: [{ taskId: '2.1' }, { taskId: '2.2' }],
    plannedChanges: 'Provision DynamoDB table with tenant-bound keys, GSIs, Streams, PITR; implement AP-01–AP-15 access patterns',
    changedFiles: [],
    auditSection: '§7',
  },
  {
    id: 'AF-52',
    title: 'Business-type value mismatch — mobile_shop vs mobileShop',
    currentEvidence: 'billing_service.dart compares against "mobile_shop" but enum.name is "mobileShop"; wire values inconsistent',
    rootCause: 'No canonical normalization at system boundaries; string literals scattered in code',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '6.18' }],
    designLinks: [{ componentId: '2', componentName: 'Tenant Context and Policy' }],
    taskLinks: [{ taskId: '1.3' }],
    plannedChanges: 'Normalize mobileShop/mobileshop/mobile_shop to one canonical wire value at all boundaries',
    changedFiles: [],
    auditSection: '§7, §13',
  },
  {
    id: 'AF-53',
    title: 'Missing dedicated test coverage for mobile shop',
    currentEvidence: 'No dedicated unit, widget, integration, or end-to-end tests for mobileShop-specific behavior; existing tests are generic retail',
    rootCause: 'Mobile-specific features were built without corresponding test suites',
    severity: 'high',
    status: 'open',
    dependencies: [],
    requirementLinks: [{ requirementId: '13.1' }, { requirementId: '13.2' }],
    designLinks: [{ componentId: '1', componentName: 'Remediation Ledger and Traceability Gate' }],
    taskLinks: [{ taskId: '18.1' }, { taskId: '18.2' }, { taskId: '18.3' }],
    plannedChanges: 'Add layered test suites: unit, widget, repository, routing, permission, Drift, sync, API-contract, and end-to-end',
    changedFiles: [],
    auditSection: '§20',
  },
];

/** The complete remediation ledger for mobileShop */
export const mobileShopRemediationLedger: RemediationLedger = {
  version: '1.0.0',
  businessType: 'mobileShop',
  auditReportPath: 'audit-reports/business-types/audit-mobileShop.md',
  createdAt: new Date().toISOString().split('T')[0],
  updatedAt: new Date().toISOString().split('T')[0],
  findings,
  relatedDefects: [],
};
