/// API Connector — connects screens to real API endpoints using the existing
/// repository pattern (feature repository → ApiClient).
///
/// Implements: ApiConnector, ApiConnectionPlan, ApiRetryMixin.
///
/// Responsibilities:
/// - Analyze screens and generate API connection code scaffolds.
/// - Generate repository method code for connecting to an API.
/// - Generate loading/error/retry state management code.
/// - Provide reusable retry logic with exponential backoff.
///
/// Requirements: 7.1, 7.2, 7.3, 7.4, 7.5
library;

import 'dart:math';

/// Represents a backend route from the Discovery Registry's API surface map.
class Route {
  /// HTTP method (GET, POST, PUT, DELETE, PATCH).
  final String method;

  /// Original route path as defined in config (e.g., '/ac/students/{id}').
  final String path;

  /// Path with parameters replaced by wildcards for matching.
  final String normalizedPath;

  /// File path of the Lambda handler.
  final String handlerFile;

  /// Whether the route requires authentication.
  final bool authenticated;

  /// Source configuration file.
  final String source;

  const Route({
    required this.method,
    required this.path,
    required this.normalizedPath,
    required this.handlerFile,
    required this.authenticated,
    required this.source,
  });

  @override
  String toString() => 'Route($method $path → $handlerFile)';
}

/// A planned API connection describing how a screen should be wired to an endpoint.
class ApiConnectionPlan {
  /// The screen file being connected.
  final String screenFile;

  /// The data entity type (e.g., 'student', 'invoice', 'product').
  final String entityType;

  /// The matched API endpoint path, if one exists.
  final String? matchedEndpoint;

  /// The HTTP method for the matched endpoint.
  final String? httpMethod;

  /// The repository class that should contain the API method.
  final String repositoryClass;

  /// The method name to generate in the repository.
  final String methodName;

  /// Whether a new backend endpoint needs to be created.
  final bool needsNewEndpoint;

  /// The vertical this screen belongs to.
  final String vertical;

  /// Additional CRUD operations needed beyond the primary match.
  final List<String> additionalOperations;

  const ApiConnectionPlan({
    required this.screenFile,
    required this.entityType,
    this.matchedEndpoint,
    this.httpMethod,
    required this.repositoryClass,
    required this.methodName,
    required this.needsNewEndpoint,
    required this.vertical,
    this.additionalOperations = const [],
  });

  @override
  String toString() =>
      'ApiConnectionPlan(screen: $screenFile, entity: $entityType, '
      'endpoint: $matchedEndpoint, needsNew: $needsNewEndpoint)';
}

/// Mixin providing reusable retry logic with exponential backoff.
///
/// Retry policy (from Requirement 7.2):
/// - Maximum 3 retry attempts.
/// - Exponential backoff starting at 1 second.
/// - Preserves user-entered form data on final failure (Requirement 7.5).
mixin ApiRetryMixin {
  /// Executes [action] with retry logic using exponential backoff.
  ///
  /// - [maxAttempts]: Maximum number of attempts (default: 3).
  /// - [initialDelay]: Starting backoff delay (default: 1 second).
  ///
  /// Returns the result of [action] on success. Throws the last exception
  /// after all retries are exhausted.
  Future<T> withRetry<T>(
    Future<T> Function() action, {
    int maxAttempts = 3,
    Duration initialDelay = const Duration(seconds: 1),
  }) async {
    Object? lastError;
    StackTrace? lastStack;

    for (int attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        return await action();
      } catch (error, stack) {
        lastError = error;
        lastStack = stack;

        // Don't delay after the final attempt
        if (attempt < maxAttempts) {
          final delay = initialDelay * pow(2, attempt - 1);
          await Future.delayed(delay);
        }
      }
    }

    // All retries exhausted — rethrow the last error
    Error.throwWithStackTrace(lastError!, lastStack!);
  }
}

/// Generates state management code for API-connected screens.
///
/// Handles:
/// - Loading state (visual indicator during API response).
/// - Error state (message on failure after retries).
/// - Retry logic (3 attempts, exponential backoff starting at 1s).
/// - Form data preservation on API failure (Requirement 7.5).
class ApiStateManager with ApiRetryMixin {
  /// Generates Dart code for a loading/error/retry state management class
  /// based on the given [plan].
  String generateStateCode(ApiConnectionPlan plan) {
    final className = '${_toPascalCase(plan.entityType)}ApiState';

    return '''
/// State management for ${plan.entityType} API operations.
/// Generated by ApiConnector for: ${plan.screenFile}
///
/// Implements:
/// - Loading state (visual indicator during API response)
/// - Error state (message on failure after retries)
/// - Retry logic (3 attempts, exponential backoff starting at 1s)
/// - Form data preservation on failure (Requirement 7.5)
class $className {
  bool isLoading = false;
  String? errorMessage;
  int _retryCount = 0;
  static const int maxRetries = 3;
  static const Duration initialBackoff = Duration(seconds: 1);

  /// Preserved form data — remains intact on API failure.
  Map<String, dynamic> _preservedFormData = {};

  /// Current navigation state — preserved across API failures.
  String? _preservedRoute;
  Map<String, dynamic>? _preservedRouteParams;

  /// Save current form data for preservation on failure.
  void preserveFormData(Map<String, dynamic> formData) {
    _preservedFormData = Map.from(formData);
  }

  /// Save current navigation state for preservation on failure.
  void preserveNavigationState(String route, [Map<String, dynamic>? params]) {
    _preservedRoute = route;
    _preservedRouteParams = params != null ? Map.from(params) : null;
  }

  /// Get preserved form data (non-null after failure).
  Map<String, dynamic> get preservedFormData => _preservedFormData;

  /// Get preserved navigation route.
  String? get preservedRoute => _preservedRoute;

  /// Get preserved route parameters.
  Map<String, dynamic>? get preservedRouteParams => _preservedRouteParams;

  /// Whether the state is in error condition.
  bool get hasError => errorMessage != null;

  /// Whether retries are still available.
  bool get canRetry => _retryCount < maxRetries;

  /// Execute an API call with loading state management and retry logic.
  Future<T?> execute<T>(Future<T> Function() apiCall) async {
    isLoading = true;
    errorMessage = null;
    _retryCount = 0;

    try {
      final result = await _executeWithRetry(apiCall);
      isLoading = false;
      return result;
    } catch (e) {
      isLoading = false;
      errorMessage = e.toString();
      // Form data and navigation state are preserved — no clearing.
      return null;
    }
  }

  /// Internal retry with exponential backoff.
  Future<T> _executeWithRetry<T>(Future<T> Function() apiCall) async {
    Object? lastError;
    for (int attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        _retryCount = attempt;
        return await apiCall();
      } catch (e) {
        lastError = e;
        if (attempt < maxRetries) {
          final delay = initialBackoff * (1 << (attempt - 1));
          await Future.delayed(delay);
        }
      }
    }
    throw lastError ?? Exception('API call failed after \$maxRetries attempts');
  }

  /// Reset state for a fresh attempt.
  void reset() {
    isLoading = false;
    errorMessage = null;
    _retryCount = 0;
    // Note: form data is NOT cleared on reset — only on explicit clear.
  }

  /// Explicitly clear preserved form data.
  void clearPreservedData() {
    _preservedFormData = {};
    _preservedRoute = null;
    _preservedRouteParams = null;
  }
}
''';
  }
}

/// Connects screens to real API endpoints using the existing repository pattern.
///
/// This class performs static analysis to determine what API connections are
/// needed for a screen, and generates the appropriate repository method code
/// and state management scaffolding.
class ApiConnector with ApiRetryMixin {
  /// Analyzes a screen and generates the API connection plan.
  ///
  /// - [screenPath]: Path to the screen file.
  /// - [content]: The Dart source content of the screen.
  /// - [availableRoutes]: Backend routes from the Discovery Registry.
  ///
  /// Returns a plan describing how to connect the screen to its API.
  ApiConnectionPlan planConnection(
    String screenPath,
    String content,
    List<Route> availableRoutes,
  ) {
    final entityType = _inferEntityType(screenPath, content);
    final vertical = _deriveVertical(screenPath);
    final repositoryClass = _inferRepositoryClass(vertical, entityType);
    final methodName = _inferMethodName(content, entityType);

    // Try to match the screen's entity to an existing endpoint
    final matchedRoute = _findMatchingRoute(
      entityType,
      vertical,
      availableRoutes,
    );

    return ApiConnectionPlan(
      screenFile: screenPath,
      entityType: entityType,
      matchedEndpoint: matchedRoute?.path,
      httpMethod: matchedRoute?.method,
      repositoryClass: repositoryClass,
      methodName: methodName,
      needsNewEndpoint: matchedRoute == null,
      vertical: vertical,
      additionalOperations: _inferAdditionalOperations(content),
    );
  }

  /// Generates repository method code for connecting to an API.
  ///
  /// Follows the existing repository pattern: feature repository → ApiClient.
  /// Reference: `ac_repository.dart` structure.
  String generateRepositoryMethod(ApiConnectionPlan plan) {
    final returnType = _toPascalCase(plan.entityType);
    final endpoint =
        plan.matchedEndpoint ?? '/${plan.vertical}/${plan.entityType}s';
    final method = plan.httpMethod ?? 'GET';

    final buffer = StringBuffer();

    buffer.writeln(
      '  // ══════════════════════════════════════════════════════════',
    );
    buffer.writeln(
      '  // ${plan.entityType.toUpperCase()} — Auto-generated API connection',
    );
    buffer.writeln(
      '  // ══════════════════════════════════════════════════════════',
    );
    buffer.writeln();

    switch (method.toUpperCase()) {
      case 'GET':
        buffer.writeln(_generateGetMethod(plan, returnType, endpoint));
      case 'POST':
        buffer.writeln(_generatePostMethod(plan, returnType, endpoint));
      case 'PUT':
        buffer.writeln(_generatePutMethod(plan, returnType, endpoint));
      case 'DELETE':
        buffer.writeln(_generateDeleteMethod(plan, endpoint));
      default:
        buffer.writeln(_generateGetMethod(plan, returnType, endpoint));
    }

    // Generate additional CRUD methods if needed
    for (final op in plan.additionalOperations) {
      buffer.writeln();
      switch (op) {
        case 'list':
          buffer.writeln(_generateListMethod(plan, returnType, endpoint));
        case 'create':
          buffer.writeln(_generatePostMethod(plan, returnType, endpoint));
        case 'update':
          buffer.writeln(_generatePutMethod(plan, returnType, endpoint));
        case 'delete':
          buffer.writeln(_generateDeleteMethod(plan, endpoint));
      }
    }

    return buffer.toString();
  }

  /// Generates loading/error/retry state management code for a screen.
  String generateStateManagement(ApiConnectionPlan plan) {
    final stateManager = ApiStateManager();
    return stateManager.generateStateCode(plan);
  }

  // ─── Private helpers ────────────────────────────────────────────────────────

  /// Infers the entity type from the screen file path and content.
  String _inferEntityType(String screenPath, String content) {
    final fileName = screenPath.split('/').last.split('\\').last;

    // Remove common suffixes/prefixes to extract entity name
    var name = fileName
        .replaceAll('_screen.dart', '')
        .replaceAll('_page.dart', '')
        .replaceAll('_management_screen.dart', '')
        .replaceAll('_list_screen.dart', '')
        .replaceAll('_detail_screen.dart', '')
        .replaceAll('_create_screen.dart', '')
        .replaceAll('_edit_screen.dart', '');

    // Remove vertical prefix if present (e.g., 'ac_' for academic_coaching)
    final prefixMatch = RegExp(r'^[a-z]+_').firstMatch(name);
    if (prefixMatch != null && name.length > prefixMatch.end) {
      final withoutPrefix = name.substring(prefixMatch.end);
      // Only strip if the remaining part is meaningful (>2 chars)
      if (withoutPrefix.length > 2) {
        name = withoutPrefix;
      }
    }

    return name;
  }

  /// Derives the vertical (business type) from a file path.
  String _deriveVertical(String path) {
    final normalized = path.replaceAll('\\', '/');
    final featureMatch = RegExp(
      r'lib/features/([^/]+)/',
    ).firstMatch(normalized);
    if (featureMatch != null) {
      return featureMatch.group(1)!;
    }
    return 'core/general';
  }

  /// Infers the repository class name from the vertical and entity type.
  String _inferRepositoryClass(String vertical, String entityType) {
    final prefix = _toPascalCase(vertical);
    return '${prefix}Repository';
  }

  /// Infers the method name based on screen content analysis.
  String _inferMethodName(String content, String entityType) {
    final pascalEntity = _toPascalCase(entityType);

    // Detect CRUD intent from screen content
    if (_containsPattern(content, ['ListView', 'DataTable', 'list', 'items'])) {
      return 'list${pascalEntity}s';
    }
    if (_containsPattern(content, ['Form', 'TextFormField', 'create', 'add'])) {
      return 'create$pascalEntity';
    }
    if (_containsPattern(content, ['edit', 'update', 'modify'])) {
      return 'update$pascalEntity';
    }
    if (_containsPattern(content, ['detail', 'view', 'show'])) {
      return 'get$pascalEntity';
    }
    if (_containsPattern(content, ['delete', 'remove'])) {
      return 'delete$pascalEntity';
    }

    // Default to a list method for general screens
    return 'get$pascalEntity';
  }

  /// Finds a matching route from available routes based on entity type.
  Route? _findMatchingRoute(
    String entityType,
    String vertical,
    List<Route> availableRoutes,
  ) {
    final entityPlural = '${entityType}s';
    final normalizedEntity = entityType.replaceAll('_', '');
    final normalizedPlural = '${normalizedEntity}s';

    // Try exact match on path segments
    for (final route in availableRoutes) {
      final pathSegments = route.path.split('/').where((s) => s.isNotEmpty);
      for (final segment in pathSegments) {
        final normalizedSegment = segment
            .replaceAll('_', '')
            .replaceAll('-', '');
        if (normalizedSegment == normalizedEntity ||
            normalizedSegment == normalizedPlural) {
          return route;
        }
      }
    }

    // Try partial match with vertical prefix
    for (final route in availableRoutes) {
      final normalizedPath = route.path.toLowerCase().replaceAll('-', '_');
      if (normalizedPath.contains(entityType) ||
          normalizedPath.contains(entityPlural)) {
        return route;
      }
    }

    return null;
  }

  /// Infers additional CRUD operations needed based on screen content.
  List<String> _inferAdditionalOperations(String content) {
    final operations = <String>[];

    if (_containsPattern(content, ['ListView', 'DataTable', 'GridView'])) {
      operations.add('list');
    }
    if (_containsPattern(content, ['TextFormField', 'Form(', 'FormBuilder'])) {
      if (_containsPattern(content, ['create', 'add', 'new'])) {
        operations.add('create');
      }
      if (_containsPattern(content, ['edit', 'update', 'save'])) {
        operations.add('update');
      }
    }
    if (_containsPattern(content, ['delete', 'remove', 'Dismissible'])) {
      operations.add('delete');
    }

    return operations;
  }

  /// Checks if content contains any of the given patterns.
  bool _containsPattern(String content, List<String> patterns) {
    final lower = content.toLowerCase();
    return patterns.any((p) => lower.contains(p.toLowerCase()));
  }

  // ─── Code generation helpers ────────────────────────────────────────────────

  String _generateGetMethod(
    ApiConnectionPlan plan,
    String returnType,
    String endpoint,
  ) {
    return '''  Future<$returnType> ${plan.methodName}(String id) async {
    final response = await _apiClient.get('$endpoint/\$id');
    if (response.statusCode == 200) {
      final raw = response.data ?? {};
      return $returnType.fromJson(raw['data'] ?? raw);
    }
    throw Exception('Failed to load ${plan.entityType}: \${response.error}');
  }''';
  }

  String _generateListMethod(
    ApiConnectionPlan plan,
    String returnType,
    String endpoint,
  ) {
    return '''  Future<List<$returnType>> list${_toPascalCase(plan.entityType)}s({
    int page = 1,
    int limit = 20,
    String? search,
  }) async {
    final queryParams = <String, String>{
      'page': page.toString(),
      'limit': limit.toString(),
    };
    if (search != null) queryParams['search'] = search;

    final response = await _apiClient.get(
      '$endpoint',
      queryParameters: queryParams,
    );

    if (response.statusCode == 200) {
      final data = response.data ?? {};
      final List<dynamic> items = data['data'] ?? data['items'] ?? [];
      return items.map((json) => $returnType.fromJson(json)).toList();
    }
    throw Exception('Failed to load ${plan.entityType}s: \${response.error}');
  }''';
  }

  String _generatePostMethod(
    ApiConnectionPlan plan,
    String returnType,
    String endpoint,
  ) {
    return '''  Future<$returnType> create${_toPascalCase(plan.entityType)}(Map<String, dynamic> data) async {
    final response = await _apiClient.post('$endpoint', body: data);
    if (response.statusCode == 201 || response.statusCode == 200) {
      final raw = response.data ?? {};
      return $returnType.fromJson(raw['data'] ?? raw);
    }
    throw Exception('Failed to create ${plan.entityType}: \${response.error}');
  }''';
  }

  String _generatePutMethod(
    ApiConnectionPlan plan,
    String returnType,
    String endpoint,
  ) {
    return '''  Future<$returnType> update${_toPascalCase(plan.entityType)}(String id, Map<String, dynamic> data) async {
    final response = await _apiClient.put('$endpoint/\$id', body: data);
    if (response.statusCode == 200) {
      final raw = response.data ?? {};
      return $returnType.fromJson(raw['data'] ?? raw);
    }
    throw Exception('Failed to update ${plan.entityType}: \${response.error}');
  }''';
  }

  String _generateDeleteMethod(ApiConnectionPlan plan, String endpoint) {
    return '''  Future<void> delete${_toPascalCase(plan.entityType)}(String id) async {
    final response = await _apiClient.delete('$endpoint/\$id');
    if (response.statusCode != 200) {
      throw Exception('Failed to delete ${plan.entityType}: \${response.error}');
    }
  }''';
  }
}

/// Generates the code scaffold for a missing backend endpoint.
///
/// Follows the `authorizedHandler` pattern from:
/// `my-backend/src/middleware/handler-wrapper.ts`
///
/// Includes: input validation, tenant context extraction, structured error responses.
class EndpointGenerator {
  /// Generates a new Lambda handler following the project's authorizedHandler pattern.
  ///
  /// - [plan]: The API connection plan describing the required endpoint.
  ///
  /// Returns TypeScript handler code matching the project conventions.
  String generateHandler(ApiConnectionPlan plan) {
    final entityPascal = _toPascalCase(plan.entityType);
    final entityCamel = _toCamelCase(plan.entityType);
    final handlerName = '${plan.methodName}Handler';

    return '''
// ============================================================================
// ${entityPascal} Handler — Auto-generated endpoint
// ============================================================================
// Follows authorizedHandler pattern with:
// - Input validation (Zod schema)
// - Tenant context extraction from auth
// - Structured error responses with correlation IDs
// ============================================================================

import { authorizedHandler } from '../middleware/handler-wrapper';
import { UserRole } from '../middleware/auth-types';
import { z } from 'zod';
import { ${entityCamel}Repository } from '../repositories/${plan.entityType}-repository';
import { success, badRequest, serverError } from '../utils/response';

const ${entityCamel}Schema = z.object({
  // TODO: Define input validation schema for ${plan.entityType}
  name: z.string().min(1).max(255),
});

export const $handlerName = authorizedHandler(
  [UserRole.OWNER, UserRole.ADMIN, UserRole.STAFF],
  async (event, context, auth) => {
    const { tenantId } = auth;
    const correlationId = event.headers['x-correlation-id'] || context.awsRequestId;

    try {
      const body = JSON.parse(event.body || '{}');
      const validated = ${entityCamel}Schema.safeParse(body);

      if (!validated.success) {
        return badRequest({
          error: 'Validation failed',
          details: validated.error.issues,
          correlationId,
        });
      }

      const result = await ${entityCamel}Repository.${plan.methodName}(
        tenantId,
        validated.data,
      );

      return success({
        data: result,
        correlationId,
      });
    } catch (error: any) {
      console.error('[${handlerName}] Error:', {
        correlationId,
        tenantId,
        error: error.message,
      });

      return serverError({
        error: 'Internal server error',
        correlationId,
      });
    }
  },
);
''';
  }
}

// ─── Utility functions ────────────────────────────────────────────────────────

/// Converts a snake_case or kebab-case string to PascalCase.
String _toPascalCase(String input) {
  return input
      .split(RegExp(r'[_\-/]'))
      .where((s) => s.isNotEmpty)
      .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
      .join();
}

/// Converts a snake_case or kebab-case string to camelCase.
String _toCamelCase(String input) {
  final pascal = _toPascalCase(input);
  if (pascal.isEmpty) return pascal;
  return pascal[0].toLowerCase() + pascal.substring(1);
}
