// Mocks generated by Mockito 5.4.6 from annotations
// in dukanx/test/features/ai_assistant/services/recommendation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i15;

import 'package:amazon_cognito_identity_dart_2/cognito.dart' as _i13;
import 'package:dukanx/core/database/app_database.dart' as _i2;
import 'package:dukanx/core/error/error_handler.dart' as _i4;
import 'package:dukanx/core/repository/bills_repository.dart' as _i11;
import 'package:dukanx/core/repository/products_repository.dart' as _i7;
import 'package:dukanx/core/services/event_dispatcher.dart' as _i5;
import 'package:dukanx/core/session/session_manager.dart' as _i6;
import 'package:dukanx/core/sync/sync_manager.dart' as _i3;
import 'package:dukanx/models/bill.dart' as _i12;
import 'package:dukanx/models/business_type.dart' as _i14;
import 'package:dukanx/models/reorder_prediction.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncManager_1 extends _i1.SmartFake implements _i3.SyncManager {
  _FakeSyncManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeErrorHandler_2 extends _i1.SmartFake implements _i4.ErrorHandler {
  _FakeErrorHandler_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventDispatcher_3 extends _i1.SmartFake
    implements _i5.EventDispatcher {
  _FakeEventDispatcher_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRepositoryResult_4<T> extends _i1.SmartFake
    implements _i4.RepositoryResult<T> {
  _FakeRepositoryResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserSession_5 extends _i1.SmartFake implements _i6.UserSession {
  _FakeUserSession_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i7.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i3.SyncManager get syncManager =>
      (super.noSuchMethod(
            Invocation.getter(#syncManager),
            returnValue: _FakeSyncManager_1(
              this,
              Invocation.getter(#syncManager),
            ),
          )
          as _i3.SyncManager);

  @override
  _i4.ErrorHandler get errorHandler =>
      (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: _FakeErrorHandler_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          )
          as _i4.ErrorHandler);

  @override
  _i5.EventDispatcher get eventDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#eventDispatcher),
            returnValue: _FakeEventDispatcher_3(
              this,
              Invocation.getter(#eventDispatcher),
            ),
          )
          as _i5.EventDispatcher);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i9.Future<_i4.RepositoryResult<_i7.Product>> createProduct({
    required String? userId,
    required String? name,
    String? sku,
    String? barcode,
    String? category,
    String? unit = 'pcs',
    required double? sellingPrice,
    double? costPrice = 0.0,
    double? taxRate = 0.0,
    double? stockQuantity = 0.0,
    double? lowStockThreshold = 10.0,
    String? size,
    String? color,
    String? brand,
    String? hsnCode,
    List<String>? altBarcodes,
    String? drugSchedule,
    String? groupId,
    Map<String, String>? variantAttributes,
    List<Map<String, dynamic>>? initialBatches,
    List<String>? initialImeis,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [], {
              #userId: userId,
              #name: name,
              #sku: sku,
              #barcode: barcode,
              #category: category,
              #unit: unit,
              #sellingPrice: sellingPrice,
              #costPrice: costPrice,
              #taxRate: taxRate,
              #stockQuantity: stockQuantity,
              #lowStockThreshold: lowStockThreshold,
              #size: size,
              #color: color,
              #brand: brand,
              #hsnCode: hsnCode,
              #altBarcodes: altBarcodes,
              #drugSchedule: drugSchedule,
              #groupId: groupId,
              #variantAttributes: variantAttributes,
              #initialBatches: initialBatches,
              #initialImeis: initialImeis,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<_i7.Product>>.value(
              _FakeRepositoryResult_4<_i7.Product>(
                this,
                Invocation.method(#createProduct, [], {
                  #userId: userId,
                  #name: name,
                  #sku: sku,
                  #barcode: barcode,
                  #category: category,
                  #unit: unit,
                  #sellingPrice: sellingPrice,
                  #costPrice: costPrice,
                  #taxRate: taxRate,
                  #stockQuantity: stockQuantity,
                  #lowStockThreshold: lowStockThreshold,
                  #size: size,
                  #color: color,
                  #brand: brand,
                  #hsnCode: hsnCode,
                  #altBarcodes: altBarcodes,
                  #drugSchedule: drugSchedule,
                  #groupId: groupId,
                  #variantAttributes: variantAttributes,
                  #initialBatches: initialBatches,
                  #initialImeis: initialImeis,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i7.Product>>);

  @override
  _i9.Future<_i4.RepositoryResult<_i7.Product?>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i4.RepositoryResult<_i7.Product?>>.value(
              _FakeRepositoryResult_4<_i7.Product?>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i7.Product?>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i7.Product>>> getAll({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#userId: userId}),
            returnValue:
                _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i7.Product>>(
                    this,
                    Invocation.method(#getAll, [], {#userId: userId}),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>);

  @override
  _i9.Stream<List<_i7.Product>> watchAll({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {#userId: userId}),
            returnValue: _i9.Stream<List<_i7.Product>>.empty(),
          )
          as _i9.Stream<List<_i7.Product>>);

  @override
  _i9.Stream<List<String>> watchUniqueCategories({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchUniqueCategories, [], {#userId: userId}),
            returnValue: _i9.Stream<List<String>>.empty(),
          )
          as _i9.Stream<List<String>>);

  @override
  _i9.Future<_i4.RepositoryResult<_i7.Product>> updateProduct(
    _i7.Product? product, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product], {#userId: userId}),
            returnValue: _i9.Future<_i4.RepositoryResult<_i7.Product>>.value(
              _FakeRepositoryResult_4<_i7.Product>(
                this,
                Invocation.method(#updateProduct, [product], {#userId: userId}),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i7.Product>>);

  @override
  _i9.Future<_i4.RepositoryResult<bool>> deleteProduct(
    String? id, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id], {#userId: userId}),
            returnValue: _i9.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#deleteProduct, [id], {#userId: userId}),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<bool>>);

  @override
  _i9.Future<_i4.RepositoryResult<_i7.Product>> adjustStock({
    required String? productId,
    required double? quantity,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #quantity: quantity,
              #userId: userId,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<_i7.Product>>.value(
              _FakeRepositoryResult_4<_i7.Product>(
                this,
                Invocation.method(#adjustStock, [], {
                  #productId: productId,
                  #quantity: quantity,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i7.Product>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i7.Product>>> getLowStockProducts({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLowStockProducts, [], {#userId: userId}),
            returnValue:
                _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i7.Product>>(
                    this,
                    Invocation.method(#getLowStockProducts, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i7.Product>>> getDeadStock({
    required String? userId,
    required int? daysUnsold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDeadStock, [], {
              #userId: userId,
              #daysUnsold: daysUnsold,
            }),
            returnValue:
                _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i7.Product>>(
                    this,
                    Invocation.method(#getDeadStock, [], {
                      #userId: userId,
                      #daysUnsold: daysUnsold,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i10.ReorderPrediction>>>
  getSmartReorderSuggestions({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSmartReorderSuggestions, [], {
              #userId: userId,
            }),
            returnValue:
                _i9.Future<
                  _i4.RepositoryResult<List<_i10.ReorderPrediction>>
                >.value(
                  _FakeRepositoryResult_4<List<_i10.ReorderPrediction>>(
                    this,
                    Invocation.method(#getSmartReorderSuggestions, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i10.ReorderPrediction>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i7.Product>>> search(
    String? query, {
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#userId: userId}),
            returnValue:
                _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>.value(
                  _FakeRepositoryResult_4<List<_i7.Product>>(
                    this,
                    Invocation.method(#search, [query], {#userId: userId}),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i7.Product>>>);

  @override
  _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>> getStockStatusSummary(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStockStatusSummary, [userId]),
            returnValue:
                _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getStockStatusSummary, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>> getSalesPerformance(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesPerformance, [userId]),
            returnValue:
                _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getSalesPerformance, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>
  getBatchesForProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchesForProduct, [productId]),
            returnValue:
                _i9.Future<
                  _i4.RepositoryResult<List<_i2.ProductBatchEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.ProductBatchEntity>>(
                    this,
                    Invocation.method(#getBatchesForProduct, [productId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>> getAllBatches(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBatches, [userId]),
            returnValue:
                _i9.Future<
                  _i4.RepositoryResult<List<_i2.ProductBatchEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.ProductBatchEntity>>(
                    this,
                    Invocation.method(#getAllBatches, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i2.ProductBatchEntity>>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i2.StockMovementEntity>>> getDamageLogs(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDamageLogs, [userId]),
            returnValue:
                _i9.Future<
                  _i4.RepositoryResult<List<_i2.StockMovementEntity>>
                >.value(
                  _FakeRepositoryResult_4<List<_i2.StockMovementEntity>>(
                    this,
                    Invocation.method(#getDamageLogs, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i2.StockMovementEntity>>>);
}

/// A class which mocks [BillsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillsRepository extends _i1.Mock implements _i11.BillsRepository {
  MockBillsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i3.SyncManager get syncManager =>
      (super.noSuchMethod(
            Invocation.getter(#syncManager),
            returnValue: _FakeSyncManager_1(
              this,
              Invocation.getter(#syncManager),
            ),
          )
          as _i3.SyncManager);

  @override
  _i4.ErrorHandler get errorHandler =>
      (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: _FakeErrorHandler_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          )
          as _i4.ErrorHandler);

  @override
  _i5.EventDispatcher get eventDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#eventDispatcher),
            returnValue: _FakeEventDispatcher_3(
              this,
              Invocation.getter(#eventDispatcher),
            ),
          )
          as _i5.EventDispatcher);

  @override
  _i9.Future<_i4.RepositoryResult<_i12.Bill>> createBill(_i12.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#createBill, [bill]),
            returnValue: _i9.Future<_i4.RepositoryResult<_i12.Bill>>.value(
              _FakeRepositoryResult_4<_i12.Bill>(
                this,
                Invocation.method(#createBill, [bill]),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i12.Bill>>);

  @override
  _i9.Future<_i4.RepositoryResult<_i12.Bill>> updateBill(
    _i12.Bill? bill, {
    String? approverId,
    String? editReason,
    DateTime? expectedUpdatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBill,
              [bill],
              {
                #approverId: approverId,
                #editReason: editReason,
                #expectedUpdatedAt: expectedUpdatedAt,
              },
            ),
            returnValue: _i9.Future<_i4.RepositoryResult<_i12.Bill>>.value(
              _FakeRepositoryResult_4<_i12.Bill>(
                this,
                Invocation.method(
                  #updateBill,
                  [bill],
                  {
                    #approverId: approverId,
                    #editReason: editReason,
                    #expectedUpdatedAt: expectedUpdatedAt,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i12.Bill>>);

  @override
  _i9.Future<_i4.RepositoryResult<_i12.Bill>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i4.RepositoryResult<_i12.Bill>>.value(
              _FakeRepositoryResult_4<_i12.Bill>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<_i12.Bill>>);

  @override
  _i9.Future<_i4.RepositoryResult<List<_i12.Bill>>> getAll({
    required String? userId,
    String? customerId,
    String? businessId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #userId: userId,
              #customerId: customerId,
              #businessId: businessId,
            }),
            returnValue:
                _i9.Future<_i4.RepositoryResult<List<_i12.Bill>>>.value(
                  _FakeRepositoryResult_4<List<_i12.Bill>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #userId: userId,
                      #customerId: customerId,
                      #businessId: businessId,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<List<_i12.Bill>>>);

  @override
  _i9.Stream<List<_i12.Bill>> watchAll({
    required String? userId,
    String? customerId,
    String? businessId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {
              #userId: userId,
              #customerId: customerId,
              #businessId: businessId,
            }),
            returnValue: _i9.Stream<List<_i12.Bill>>.empty(),
          )
          as _i9.Stream<List<_i12.Bill>>);

  @override
  _i9.Future<_i4.RepositoryResult<bool>> recordPayment({
    required String? userId,
    required String? billId,
    required double? amount,
    required String? paymentMode,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPayment, [], {
              #userId: userId,
              #billId: billId,
              #amount: amount,
              #paymentMode: paymentMode,
              #notes: notes,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#recordPayment, [], {
                  #userId: userId,
                  #billId: billId,
                  #amount: amount,
                  #paymentMode: paymentMode,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<bool>>);

  @override
  _i9.Future<_i4.RepositoryResult<bool>> deletePayment({
    required String? userId,
    required String? paymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [], {
              #userId: userId,
              #paymentId: paymentId,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#deletePayment, [], {
                  #userId: userId,
                  #paymentId: paymentId,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<bool>>);

  @override
  _i9.Future<_i4.RepositoryResult<bool>> updateBillStatus({
    required String? billId,
    required String? status,
    required double? paidAmount,
    double? cashPaid,
    double? onlinePaid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBillStatus, [], {
              #billId: billId,
              #status: status,
              #paidAmount: paidAmount,
              #cashPaid: cashPaid,
              #onlinePaid: onlinePaid,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#updateBillStatus, [], {
                  #billId: billId,
                  #status: status,
                  #paidAmount: paidAmount,
                  #cashPaid: cashPaid,
                  #onlinePaid: onlinePaid,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<bool>>);

  @override
  _i9.Future<_i4.RepositoryResult<bool>> createCorrectionRequest({
    required String? billId,
    required String? customerId,
    required String? message,
    required double? billAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCorrectionRequest, [], {
              #billId: billId,
              #customerId: customerId,
              #message: message,
              #billAmount: billAmount,
            }),
            returnValue: _i9.Future<_i4.RepositoryResult<bool>>.value(
              _FakeRepositoryResult_4<bool>(
                this,
                Invocation.method(#createCorrectionRequest, [], {
                  #billId: billId,
                  #customerId: customerId,
                  #message: message,
                  #billAmount: billAmount,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<bool>>);

  @override
  _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>> getTodaySummary(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, [userId]),
            returnValue:
                _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getTodaySummary, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>> getPurchaseVsSaleStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPurchaseVsSaleStats, [userId]),
            returnValue:
                _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>.value(
                  _FakeRepositoryResult_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getPurchaseVsSaleStats, [userId]),
                  ),
                ),
          )
          as _i9.Future<_i4.RepositoryResult<Map<String, dynamic>>>);

  @override
  _i9.Future<_i4.RepositoryResult<void>> deleteBill(
    String? billId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [billId, userId]),
            returnValue: _i9.Future<_i4.RepositoryResult<void>>.value(
              _FakeRepositoryResult_4<void>(
                this,
                Invocation.method(#deleteBill, [billId, userId]),
              ),
            ),
          )
          as _i9.Future<_i4.RepositoryResult<void>>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i6.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.UserSession get currentSession =>
      (super.noSuchMethod(
            Invocation.getter(#currentSession),
            returnValue: _FakeUserSession_5(
              this,
              Invocation.getter(#currentSession),
            ),
          )
          as _i6.UserSession);

  @override
  _i9.Future<_i13.CognitoUser?> get currentCognitoUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentCognitoUser),
            returnValue: _i9.Future<_i13.CognitoUser?>.value(),
          )
          as _i9.Future<_i13.CognitoUser?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isOwner =>
      (super.noSuchMethod(Invocation.getter(#isOwner), returnValue: false)
          as bool);

  @override
  bool get isCustomer =>
      (super.noSuchMethod(Invocation.getter(#isCustomer), returnValue: false)
          as bool);

  @override
  bool get isPatient =>
      (super.noSuchMethod(Invocation.getter(#isPatient), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isCustomerOnlyMode =>
      (super.noSuchMethod(
            Invocation.getter(#isCustomerOnlyMode),
            returnValue: false,
          )
          as bool);

  @override
  _i14.BusinessType get activeBusinessType =>
      (super.noSuchMethod(
            Invocation.getter(#activeBusinessType),
            returnValue: _i14.BusinessType.grocery,
          )
          as _i14.BusinessType);

  @override
  String get userCollectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#userCollectionPath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userCollectionPath),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> setActiveBusiness(String? businessId) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveBusiness, [businessId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> enterCustomerMode(String? vendorId) =>
      (super.noSuchMethod(
            Invocation.method(#enterCustomerMode, [vendorId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> exitCustomerMode() =>
      (super.noSuchMethod(
            Invocation.method(#exitCustomerMode, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> devBypassLogin() =>
      (super.noSuchMethod(
            Invocation.method(#devBypassLogin, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> switchShop(String? newOwnerId) =>
      (super.noSuchMethod(
            Invocation.method(#switchShop, [newOwnerId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void updateMetadata(Map<String, dynamic>? metadata) => super.noSuchMethod(
    Invocation.method(#updateMetadata, [metadata]),
    returnValueForMissingStub: null,
  );

  @override
  bool hasOwnerPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasOwnerPermission, []),
            returnValue: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
